package uciephytest.phy

import chisel3._
import chisel3.util._
import chisel3.experimental.dataview._

class RxDoutIO extends Bundle {
  val dout_0 = Output(Bool())
  val dout_1 = Output(Bool())
  val dout_2 = Output(Bool())
  val dout_3 = Output(Bool())
  val dout_4 = Output(Bool())
  val dout_5 = Output(Bool())
  val dout_6 = Output(Bool())
  val dout_7 = Output(Bool())
  val dout_8 = Output(Bool())
  val dout_9 = Output(Bool())
  val dout_10 = Output(Bool())
  val dout_11 = Output(Bool())
  val dout_12 = Output(Bool())
  val dout_13 = Output(Bool())
  val dout_14 = Output(Bool())
  val dout_15 = Output(Bool())
  val dout_16 = Output(Bool())
}

class TerminationControlIO extends Bundle {
  val zctl_0 = Input(Bool())
  val zctl_1 = Input(Bool())
  val zctl_2 = Input(Bool())
  val zctl_3 = Input(Bool())
  val zctl_4 = Input(Bool())
  val zctl_5 = Input(Bool())
  val zctl_6 = Input(Bool())
  val zctl_7 = Input(Bool())
  val zctl_8 = Input(Bool())
  val zctl_9 = Input(Bool())
  val zctl_10 = Input(Bool())
  val zctl_11 = Input(Bool())
  val zctl_12 = Input(Bool())
  val zctl_13 = Input(Bool())
  val zctl_14 = Input(Bool())
  val zctl_15 = Input(Bool())
  val zctl_16 = Input(Bool())
  val zctl_17 = Input(Bool())
  val zctl_18 = Input(Bool())
  val zctl_19 = Input(Bool())
  val zctl_20 = Input(Bool())
  val zctl_21 = Input(Bool())
  val zctl_22 = Input(Bool())
  val zctl_23 = Input(Bool())
  val zctl_24 = Input(Bool())
  val zctl_25 = Input(Bool())
  val zctl_26 = Input(Bool())
  val zctl_27 = Input(Bool())
  val zctl_28 = Input(Bool())
  val zctl_29 = Input(Bool())
  val zctl_30 = Input(Bool())
  val zctl_31 = Input(Bool())
  val zctl_32 = Input(Bool())
  val zctl_33 = Input(Bool())
  val zctl_34 = Input(Bool())
  val zctl_35 = Input(Bool())
  val zctl_36 = Input(Bool())
  val zctl_37 = Input(Bool())
  val zctl_38 = Input(Bool())
  val zctl_39 = Input(Bool())
  val zctl_40 = Input(Bool())
  val zctl_41 = Input(Bool())
  val zctl_42 = Input(Bool())
  val zctl_43 = Input(Bool())
  val zctl_44 = Input(Bool())
  val zctl_45 = Input(Bool())
  val zctl_46 = Input(Bool())
  val zctl_47 = Input(Bool())
  val zctl_48 = Input(Bool())
  val zctl_49 = Input(Bool())
  val zctl_50 = Input(Bool())
  val zctl_51 = Input(Bool())
  val zctl_52 = Input(Bool())
  val zctl_53 = Input(Bool())
  val zctl_54 = Input(Bool())
  val zctl_55 = Input(Bool())
  val zctl_56 = Input(Bool())
  val zctl_57 = Input(Bool())
  val zctl_58 = Input(Bool())
  val zctl_59 = Input(Bool())
  val zctl_60 = Input(Bool())
  val zctl_61 = Input(Bool())
  val zctl_62 = Input(Bool())
  val zctl_63 = Input(Bool())
}
