package uciephytest.phy

import chisel3._
import chisel3.util._

class DriverControlIO extends Bundle {
  val pu_ctl = new DriverPuControlIO
  val pd_ctlb = new DriverPdControlIO
  val en = Input(Bool()) 
  val en_b = Input(Bool()) 
}

class ClkDriverControlIO extends Bundle {
  val pu_ctl = new DriverPuControlIO
  val pd_ctlb = new DriverPdControlIO
}

class ClockingControlIO extends Bundle {
  // Use outputs for signals that do not need to be connected
  val misc = new MiscClockingControlIO
  val en = Input(Bits(64.W))
  val enb = Input(Bits(64.W))
}

class TxLaneIO extends Bundle {
  val injp = Input(Bool())
  val injm = Input(Bool())
  val in = Input(Bool())
  val din = new TxDinIO
  val dout = Output(Bool())
  val divclk = Output(Clock())
  val resetb = Input(Bool())
  val driver_ctl = new DriverControlIO
  val clocking_ctl = new ClockingControlIO
}

class TxLane extends RawModule {
  val io = IO(new TxLaneIO)

  val verilogBlackBox = Module(new VerilogTxLane)
  verilogBlackBox.io.injp := io.injp
  verilogBlackBox.io.injm := io.injm
  verilogBlackBox.io.in := io.in
  verilogBlackBox.io.resetb := io.resetb
  verilogBlackBox.io.din_0 :=  io.din.din_0
  verilogBlackBox.io.din_1 :=  io.din.din_1
  verilogBlackBox.io.din_2 :=  io.din.din_2
  verilogBlackBox.io.din_3 :=  io.din.din_3
  verilogBlackBox.io.din_4 :=  io.din.din_4
  verilogBlackBox.io.din_5 :=  io.din.din_5
  verilogBlackBox.io.din_6 :=  io.din.din_6
  verilogBlackBox.io.din_7 :=  io.din.din_7
  verilogBlackBox.io.din_8 :=  io.din.din_8
  verilogBlackBox.io.din_9 :=  io.din.din_9
  verilogBlackBox.io.din_10 := io.din.din_10
  verilogBlackBox.io.din_11 := io.din.din_11
  verilogBlackBox.io.din_12 := io.din.din_12
  verilogBlackBox.io.din_13 := io.din.din_13
  verilogBlackBox.io.din_14 := io.din.din_14
  verilogBlackBox.io.din_15 := io.din.din_15
  io.dout := verilogBlackBox.io.dout
  io.divclk := verilogBlackBox.io.divclk
  verilogBlackBox.io.pu_ctl_0  := io.driver_ctl.pu_ctl.pu_ctl_0
  verilogBlackBox.io.pu_ctl_1  := io.driver_ctl.pu_ctl.pu_ctl_1
  verilogBlackBox.io.pu_ctl_2  := io.driver_ctl.pu_ctl.pu_ctl_2
  verilogBlackBox.io.pu_ctl_3  := io.driver_ctl.pu_ctl.pu_ctl_3
  verilogBlackBox.io.pu_ctl_4  := io.driver_ctl.pu_ctl.pu_ctl_4
  verilogBlackBox.io.pu_ctl_5  := io.driver_ctl.pu_ctl.pu_ctl_5
  verilogBlackBox.io.pu_ctl_6  := io.driver_ctl.pu_ctl.pu_ctl_6
  verilogBlackBox.io.pu_ctl_7  := io.driver_ctl.pu_ctl.pu_ctl_7
  verilogBlackBox.io.pu_ctl_8  := io.driver_ctl.pu_ctl.pu_ctl_8
  verilogBlackBox.io.pu_ctl_9  := io.driver_ctl.pu_ctl.pu_ctl_9
  verilogBlackBox.io.pu_ctl_10 := io.driver_ctl.pu_ctl.pu_ctl_10
  verilogBlackBox.io.pu_ctl_11 := io.driver_ctl.pu_ctl.pu_ctl_11
  verilogBlackBox.io.pu_ctl_12 := io.driver_ctl.pu_ctl.pu_ctl_12
  verilogBlackBox.io.pu_ctl_13 := io.driver_ctl.pu_ctl.pu_ctl_13
  verilogBlackBox.io.pu_ctl_14 := io.driver_ctl.pu_ctl.pu_ctl_14
  verilogBlackBox.io.pu_ctl_15 := io.driver_ctl.pu_ctl.pu_ctl_15
  verilogBlackBox.io.pu_ctl_16 := io.driver_ctl.pu_ctl.pu_ctl_16
  verilogBlackBox.io.pu_ctl_17 := io.driver_ctl.pu_ctl.pu_ctl_17
  verilogBlackBox.io.pu_ctl_18 := io.driver_ctl.pu_ctl.pu_ctl_18
  verilogBlackBox.io.pu_ctl_19 := io.driver_ctl.pu_ctl.pu_ctl_19
  verilogBlackBox.io.pu_ctl_20 := io.driver_ctl.pu_ctl.pu_ctl_20
  verilogBlackBox.io.pu_ctl_21 := io.driver_ctl.pu_ctl.pu_ctl_21
  verilogBlackBox.io.pu_ctl_22 := io.driver_ctl.pu_ctl.pu_ctl_22
  verilogBlackBox.io.pu_ctl_23 := io.driver_ctl.pu_ctl.pu_ctl_23
  verilogBlackBox.io.pu_ctl_24 := io.driver_ctl.pu_ctl.pu_ctl_24
  verilogBlackBox.io.pu_ctl_25 := io.driver_ctl.pu_ctl.pu_ctl_25
  verilogBlackBox.io.pu_ctl_26 := io.driver_ctl.pu_ctl.pu_ctl_26
  verilogBlackBox.io.pu_ctl_27 := io.driver_ctl.pu_ctl.pu_ctl_27
  verilogBlackBox.io.pu_ctl_28 := io.driver_ctl.pu_ctl.pu_ctl_28
  verilogBlackBox.io.pu_ctl_29 := io.driver_ctl.pu_ctl.pu_ctl_29
  verilogBlackBox.io.pu_ctl_30 := io.driver_ctl.pu_ctl.pu_ctl_30
  verilogBlackBox.io.pu_ctl_31 := io.driver_ctl.pu_ctl.pu_ctl_31
  verilogBlackBox.io.pu_ctl_32 := io.driver_ctl.pu_ctl.pu_ctl_32
  verilogBlackBox.io.pu_ctl_33 := io.driver_ctl.pu_ctl.pu_ctl_33
  verilogBlackBox.io.pu_ctl_34 := io.driver_ctl.pu_ctl.pu_ctl_34
  verilogBlackBox.io.pu_ctl_35 := io.driver_ctl.pu_ctl.pu_ctl_35
  verilogBlackBox.io.pu_ctl_36 := io.driver_ctl.pu_ctl.pu_ctl_36
  verilogBlackBox.io.pu_ctl_37 := io.driver_ctl.pu_ctl.pu_ctl_37
  verilogBlackBox.io.pu_ctl_38 := io.driver_ctl.pu_ctl.pu_ctl_38
  verilogBlackBox.io.pu_ctl_39 := io.driver_ctl.pu_ctl.pu_ctl_39
  verilogBlackBox.io.pu_ctl_40 := io.driver_ctl.pu_ctl.pu_ctl_40
  verilogBlackBox.io.pu_ctl_41 := io.driver_ctl.pu_ctl.pu_ctl_41
  verilogBlackBox.io.pu_ctl_42 := io.driver_ctl.pu_ctl.pu_ctl_42
  verilogBlackBox.io.pu_ctl_43 := io.driver_ctl.pu_ctl.pu_ctl_43
  verilogBlackBox.io.pu_ctl_44 := io.driver_ctl.pu_ctl.pu_ctl_44
  verilogBlackBox.io.pu_ctl_45 := io.driver_ctl.pu_ctl.pu_ctl_45
  verilogBlackBox.io.pu_ctl_46 := io.driver_ctl.pu_ctl.pu_ctl_46
  verilogBlackBox.io.pu_ctl_47 := io.driver_ctl.pu_ctl.pu_ctl_47
  verilogBlackBox.io.pd_ctlb_0  := io.driver_ctl.pd_ctlb.pd_ctlb_0
  verilogBlackBox.io.pd_ctlb_1  := io.driver_ctl.pd_ctlb.pd_ctlb_1
  verilogBlackBox.io.pd_ctlb_2  := io.driver_ctl.pd_ctlb.pd_ctlb_2
  verilogBlackBox.io.pd_ctlb_3  := io.driver_ctl.pd_ctlb.pd_ctlb_3
  verilogBlackBox.io.pd_ctlb_4  := io.driver_ctl.pd_ctlb.pd_ctlb_4
  verilogBlackBox.io.pd_ctlb_5  := io.driver_ctl.pd_ctlb.pd_ctlb_5
  verilogBlackBox.io.pd_ctlb_6  := io.driver_ctl.pd_ctlb.pd_ctlb_6
  verilogBlackBox.io.pd_ctlb_7  := io.driver_ctl.pd_ctlb.pd_ctlb_7
  verilogBlackBox.io.pd_ctlb_8  := io.driver_ctl.pd_ctlb.pd_ctlb_8
  verilogBlackBox.io.pd_ctlb_9  := io.driver_ctl.pd_ctlb.pd_ctlb_9
  verilogBlackBox.io.pd_ctlb_10 := io.driver_ctl.pd_ctlb.pd_ctlb_10
  verilogBlackBox.io.pd_ctlb_11 := io.driver_ctl.pd_ctlb.pd_ctlb_11
  verilogBlackBox.io.pd_ctlb_12 := io.driver_ctl.pd_ctlb.pd_ctlb_12
  verilogBlackBox.io.pd_ctlb_13 := io.driver_ctl.pd_ctlb.pd_ctlb_13
  verilogBlackBox.io.pd_ctlb_14 := io.driver_ctl.pd_ctlb.pd_ctlb_14
  verilogBlackBox.io.pd_ctlb_15 := io.driver_ctl.pd_ctlb.pd_ctlb_15
  verilogBlackBox.io.pd_ctlb_16 := io.driver_ctl.pd_ctlb.pd_ctlb_16
  verilogBlackBox.io.pd_ctlb_17 := io.driver_ctl.pd_ctlb.pd_ctlb_17
  verilogBlackBox.io.pd_ctlb_18 := io.driver_ctl.pd_ctlb.pd_ctlb_18
  verilogBlackBox.io.pd_ctlb_19 := io.driver_ctl.pd_ctlb.pd_ctlb_19
  verilogBlackBox.io.pd_ctlb_20 := io.driver_ctl.pd_ctlb.pd_ctlb_20
  verilogBlackBox.io.pd_ctlb_21 := io.driver_ctl.pd_ctlb.pd_ctlb_21
  verilogBlackBox.io.pd_ctlb_22 := io.driver_ctl.pd_ctlb.pd_ctlb_22
  verilogBlackBox.io.pd_ctlb_23 := io.driver_ctl.pd_ctlb.pd_ctlb_23
  verilogBlackBox.io.pd_ctlb_24 := io.driver_ctl.pd_ctlb.pd_ctlb_24
  verilogBlackBox.io.pd_ctlb_25 := io.driver_ctl.pd_ctlb.pd_ctlb_25
  verilogBlackBox.io.pd_ctlb_26 := io.driver_ctl.pd_ctlb.pd_ctlb_26
  verilogBlackBox.io.pd_ctlb_27 := io.driver_ctl.pd_ctlb.pd_ctlb_27
  verilogBlackBox.io.pd_ctlb_28 := io.driver_ctl.pd_ctlb.pd_ctlb_28
  verilogBlackBox.io.pd_ctlb_29 := io.driver_ctl.pd_ctlb.pd_ctlb_29
  verilogBlackBox.io.pd_ctlb_30 := io.driver_ctl.pd_ctlb.pd_ctlb_30
  verilogBlackBox.io.pd_ctlb_31 := io.driver_ctl.pd_ctlb.pd_ctlb_31
  verilogBlackBox.io.pd_ctlb_32 := io.driver_ctl.pd_ctlb.pd_ctlb_32
  verilogBlackBox.io.pd_ctlb_33 := io.driver_ctl.pd_ctlb.pd_ctlb_33
  verilogBlackBox.io.pd_ctlb_34 := io.driver_ctl.pd_ctlb.pd_ctlb_34
  verilogBlackBox.io.pd_ctlb_35 := io.driver_ctl.pd_ctlb.pd_ctlb_35
  verilogBlackBox.io.pd_ctlb_36 := io.driver_ctl.pd_ctlb.pd_ctlb_36
  verilogBlackBox.io.pd_ctlb_37 := io.driver_ctl.pd_ctlb.pd_ctlb_37
  verilogBlackBox.io.pd_ctlb_38 := io.driver_ctl.pd_ctlb.pd_ctlb_38
  verilogBlackBox.io.pd_ctlb_39 := io.driver_ctl.pd_ctlb.pd_ctlb_39
  verilogBlackBox.io.pd_ctlb_40 := io.driver_ctl.pd_ctlb.pd_ctlb_40
  verilogBlackBox.io.pd_ctlb_41 := io.driver_ctl.pd_ctlb.pd_ctlb_41
  verilogBlackBox.io.pd_ctlb_42 := io.driver_ctl.pd_ctlb.pd_ctlb_42
  verilogBlackBox.io.pd_ctlb_43 := io.driver_ctl.pd_ctlb.pd_ctlb_43
  verilogBlackBox.io.pd_ctlb_44 := io.driver_ctl.pd_ctlb.pd_ctlb_44
  verilogBlackBox.io.pd_ctlb_45 := io.driver_ctl.pd_ctlb.pd_ctlb_45
  verilogBlackBox.io.pd_ctlb_46 := io.driver_ctl.pd_ctlb.pd_ctlb_46
  verilogBlackBox.io.pd_ctlb_47 := io.driver_ctl.pd_ctlb.pd_ctlb_47
  verilogBlackBox.io.en := io.driver_ctl.en
  verilogBlackBox.io.en_b := io.driver_ctl.en_b
  verilogBlackBox.io.band_ctrl_0 := io.clocking_ctl.misc.band_ctrl(0)
  verilogBlackBox.io.band_ctrl_1 := io.clocking_ctl.misc.band_ctrl(1)
  verilogBlackBox.io.band_ctrlb_0 := io.clocking_ctl.misc.band_ctrlb(0)
  verilogBlackBox.io.band_ctrlb_1 := io.clocking_ctl.misc.band_ctrlb(1)
  verilogBlackBox.io.band_sel_0 := io.clocking_ctl.misc.band_sel(0)
  verilogBlackBox.io.band_sel_1 := io.clocking_ctl.misc.band_sel(1)
  verilogBlackBox.io.band_selb_0 := io.clocking_ctl.misc.band_selb(0)
  verilogBlackBox.io.band_selb_1 := io.clocking_ctl.misc.band_selb(1)
  verilogBlackBox.io.mix_en_0 := io.clocking_ctl.misc.mix_en(0)
  verilogBlackBox.io.mix_en_1 := io.clocking_ctl.misc.mix_en(1)
  verilogBlackBox.io.mix_en_2 := io.clocking_ctl.misc.mix_en(2)
  verilogBlackBox.io.mix_en_3 := io.clocking_ctl.misc.mix_en(3)
  verilogBlackBox.io.mix_en_4 := io.clocking_ctl.misc.mix_en(4)
  verilogBlackBox.io.mix_en_5 := io.clocking_ctl.misc.mix_en(5)
  verilogBlackBox.io.mix_en_6 := io.clocking_ctl.misc.mix_en(6)
  verilogBlackBox.io.mix_en_7 := io.clocking_ctl.misc.mix_en(7)
  verilogBlackBox.io.mix_en_8 := io.clocking_ctl.misc.mix_en(8)
  verilogBlackBox.io.mix_en_9 := io.clocking_ctl.misc.mix_en(9)
  verilogBlackBox.io.mix_en_10 := io.clocking_ctl.misc.mix_en(10)
  verilogBlackBox.io.mix_en_11 := io.clocking_ctl.misc.mix_en(11)
  verilogBlackBox.io.mix_en_12 := io.clocking_ctl.misc.mix_en(12)
  verilogBlackBox.io.mix_en_13 := io.clocking_ctl.misc.mix_en(13)
  verilogBlackBox.io.mix_en_14 := io.clocking_ctl.misc.mix_en(14)
  verilogBlackBox.io.mix_en_15 := io.clocking_ctl.misc.mix_en(15)
  verilogBlackBox.io.mix_enb_0 := io.clocking_ctl.misc.mix_enb(0)
  verilogBlackBox.io.mix_enb_1 := io.clocking_ctl.misc.mix_enb(1)
  verilogBlackBox.io.mix_enb_2 := io.clocking_ctl.misc.mix_enb(2)
  verilogBlackBox.io.mix_enb_3 := io.clocking_ctl.misc.mix_enb(3)
  verilogBlackBox.io.mix_enb_4 := io.clocking_ctl.misc.mix_enb(4)
  verilogBlackBox.io.mix_enb_5 := io.clocking_ctl.misc.mix_enb(5)
  verilogBlackBox.io.mix_enb_6 := io.clocking_ctl.misc.mix_enb(6)
  verilogBlackBox.io.mix_enb_7 := io.clocking_ctl.misc.mix_enb(7)
  verilogBlackBox.io.mix_enb_8 := io.clocking_ctl.misc.mix_enb(8)
  verilogBlackBox.io.mix_enb_9 := io.clocking_ctl.misc.mix_enb(9)
  verilogBlackBox.io.mix_enb_10 := io.clocking_ctl.misc.mix_enb(10)
  verilogBlackBox.io.mix_enb_11 := io.clocking_ctl.misc.mix_enb(11)
  verilogBlackBox.io.mix_enb_12 := io.clocking_ctl.misc.mix_enb(12)
  verilogBlackBox.io.mix_enb_13 := io.clocking_ctl.misc.mix_enb(13)
  verilogBlackBox.io.mix_enb_14 := io.clocking_ctl.misc.mix_enb(14)
  verilogBlackBox.io.mix_enb_15 := io.clocking_ctl.misc.mix_enb(15)
  verilogBlackBox.io.mux_en_0 := io.clocking_ctl.misc.mux_en(0)
  verilogBlackBox.io.mux_en_1 := io.clocking_ctl.misc.mux_en(1)
  verilogBlackBox.io.mux_en_2 := io.clocking_ctl.misc.mux_en(2)
  verilogBlackBox.io.mux_en_3 := io.clocking_ctl.misc.mux_en(3)
  verilogBlackBox.io.mux_en_4 := io.clocking_ctl.misc.mux_en(4)
  verilogBlackBox.io.mux_en_5 := io.clocking_ctl.misc.mux_en(5)
  verilogBlackBox.io.mux_en_6 := io.clocking_ctl.misc.mux_en(6)
  verilogBlackBox.io.mux_en_7 := io.clocking_ctl.misc.mux_en(7)
  verilogBlackBox.io.mux_enb_0 := io.clocking_ctl.misc.mux_enb(0)
  verilogBlackBox.io.mux_enb_1 := io.clocking_ctl.misc.mux_enb(1)
  verilogBlackBox.io.mux_enb_2 := io.clocking_ctl.misc.mux_enb(2)
  verilogBlackBox.io.mux_enb_3 := io.clocking_ctl.misc.mux_enb(3)
  verilogBlackBox.io.mux_enb_4 := io.clocking_ctl.misc.mux_enb(4)
  verilogBlackBox.io.mux_enb_5 := io.clocking_ctl.misc.mux_enb(5)
  verilogBlackBox.io.mux_enb_6 := io.clocking_ctl.misc.mux_enb(6)
  verilogBlackBox.io.mux_enb_7 := io.clocking_ctl.misc.mux_enb(7)
  verilogBlackBox.io.ph_sel_0 := io.clocking_ctl.misc.ph_sel(0)
  verilogBlackBox.io.ph_sel_1 := io.clocking_ctl.misc.ph_sel(1)
  verilogBlackBox.io.ph_selb_0 := io.clocking_ctl.misc.ph_selb(0)
  verilogBlackBox.io.ph_selb_1 := io.clocking_ctl.misc.ph_selb(1)
  verilogBlackBox.io.ilro_en_0 := io.clocking_ctl.en(0)
  verilogBlackBox.io.ilro_en_1 := io.clocking_ctl.en(1)
  verilogBlackBox.io.ilro_en_2 := io.clocking_ctl.en(2)
  verilogBlackBox.io.ilro_en_3 := io.clocking_ctl.en(3)
  verilogBlackBox.io.ilro_en_4 := io.clocking_ctl.en(4)
  verilogBlackBox.io.ilro_en_5 := io.clocking_ctl.en(5)
  verilogBlackBox.io.ilro_en_6 := io.clocking_ctl.en(6)
  verilogBlackBox.io.ilro_en_7 := io.clocking_ctl.en(7)
  verilogBlackBox.io.ilro_en_8 := io.clocking_ctl.en(8)
  verilogBlackBox.io.ilro_en_9 := io.clocking_ctl.en(9)
  verilogBlackBox.io.ilro_en_10 := io.clocking_ctl.en(10)
  verilogBlackBox.io.ilro_en_11 := io.clocking_ctl.en(11)
  verilogBlackBox.io.ilro_en_12 := io.clocking_ctl.en(12)
  verilogBlackBox.io.ilro_en_13 := io.clocking_ctl.en(13)
  verilogBlackBox.io.ilro_en_14 := io.clocking_ctl.en(14)
  verilogBlackBox.io.ilro_en_15 := io.clocking_ctl.en(15)
  verilogBlackBox.io.ilro_en_16 := io.clocking_ctl.en(16)
  verilogBlackBox.io.ilro_en_17 := io.clocking_ctl.en(17)
  verilogBlackBox.io.ilro_en_18 := io.clocking_ctl.en(18)
  verilogBlackBox.io.ilro_en_19 := io.clocking_ctl.en(19)
  verilogBlackBox.io.ilro_en_20 := io.clocking_ctl.en(20)
  verilogBlackBox.io.ilro_en_21 := io.clocking_ctl.en(21)
  verilogBlackBox.io.ilro_en_22 := io.clocking_ctl.en(22)
  verilogBlackBox.io.ilro_en_23 := io.clocking_ctl.en(23)
  verilogBlackBox.io.ilro_en_24 := io.clocking_ctl.en(24)
  verilogBlackBox.io.ilro_en_25 := io.clocking_ctl.en(25)
  verilogBlackBox.io.ilro_en_26 := io.clocking_ctl.en(26)
  verilogBlackBox.io.ilro_en_27 := io.clocking_ctl.en(27)
  verilogBlackBox.io.ilro_en_28 := io.clocking_ctl.en(28)
  verilogBlackBox.io.ilro_en_29 := io.clocking_ctl.en(29)
  verilogBlackBox.io.ilro_en_30 := io.clocking_ctl.en(30)
  verilogBlackBox.io.ilro_en_31 := io.clocking_ctl.en(31)
  verilogBlackBox.io.ilro_en_32 := io.clocking_ctl.en(32)
  verilogBlackBox.io.ilro_en_33 := io.clocking_ctl.en(33)
  verilogBlackBox.io.ilro_en_34 := io.clocking_ctl.en(34)
  verilogBlackBox.io.ilro_en_35 := io.clocking_ctl.en(35)
  verilogBlackBox.io.ilro_en_36 := io.clocking_ctl.en(36)
  verilogBlackBox.io.ilro_en_37 := io.clocking_ctl.en(37)
  verilogBlackBox.io.ilro_en_38 := io.clocking_ctl.en(38)
  verilogBlackBox.io.ilro_en_39 := io.clocking_ctl.en(39)
  verilogBlackBox.io.ilro_en_40 := io.clocking_ctl.en(40)
  verilogBlackBox.io.ilro_en_41 := io.clocking_ctl.en(41)
  verilogBlackBox.io.ilro_en_42 := io.clocking_ctl.en(42)
  verilogBlackBox.io.ilro_en_43 := io.clocking_ctl.en(43)
  verilogBlackBox.io.ilro_en_44 := io.clocking_ctl.en(44)
  verilogBlackBox.io.ilro_en_45 := io.clocking_ctl.en(45)
  verilogBlackBox.io.ilro_en_46 := io.clocking_ctl.en(46)
  verilogBlackBox.io.ilro_en_47 := io.clocking_ctl.en(47)
  verilogBlackBox.io.ilro_en_48 := io.clocking_ctl.en(48)
  verilogBlackBox.io.ilro_en_49 := io.clocking_ctl.en(49)
  verilogBlackBox.io.ilro_en_50 := io.clocking_ctl.en(50)
  verilogBlackBox.io.ilro_en_51 := io.clocking_ctl.en(51)
  verilogBlackBox.io.ilro_en_52 := io.clocking_ctl.en(52)
  verilogBlackBox.io.ilro_en_53 := io.clocking_ctl.en(53)
  verilogBlackBox.io.ilro_en_54 := io.clocking_ctl.en(54)
  verilogBlackBox.io.ilro_en_55 := io.clocking_ctl.en(55)
  verilogBlackBox.io.ilro_en_56 := io.clocking_ctl.en(56)
  verilogBlackBox.io.ilro_en_57 := io.clocking_ctl.en(57)
  verilogBlackBox.io.ilro_en_58 := io.clocking_ctl.en(58)
  verilogBlackBox.io.ilro_en_59 := io.clocking_ctl.en(59)
  verilogBlackBox.io.ilro_en_60 := io.clocking_ctl.en(60)
  verilogBlackBox.io.ilro_en_61 := io.clocking_ctl.en(61)
  verilogBlackBox.io.ilro_en_62 := io.clocking_ctl.en(62)
  verilogBlackBox.io.ilro_en_63 := io.clocking_ctl.en(63)
  verilogBlackBox.io.ilro_enb_0 := io.clocking_ctl.enb(0)
  verilogBlackBox.io.ilro_enb_1 := io.clocking_ctl.enb(1)
  verilogBlackBox.io.ilro_enb_2 := io.clocking_ctl.enb(2)
  verilogBlackBox.io.ilro_enb_3 := io.clocking_ctl.enb(3)
  verilogBlackBox.io.ilro_enb_4 := io.clocking_ctl.enb(4)
  verilogBlackBox.io.ilro_enb_5 := io.clocking_ctl.enb(5)
  verilogBlackBox.io.ilro_enb_6 := io.clocking_ctl.enb(6)
  verilogBlackBox.io.ilro_enb_7 := io.clocking_ctl.enb(7)
  verilogBlackBox.io.ilro_enb_8 := io.clocking_ctl.enb(8)
  verilogBlackBox.io.ilro_enb_9 := io.clocking_ctl.enb(9)
  verilogBlackBox.io.ilro_enb_10 := io.clocking_ctl.enb(10)
  verilogBlackBox.io.ilro_enb_11 := io.clocking_ctl.enb(11)
  verilogBlackBox.io.ilro_enb_12 := io.clocking_ctl.enb(12)
  verilogBlackBox.io.ilro_enb_13 := io.clocking_ctl.enb(13)
  verilogBlackBox.io.ilro_enb_14 := io.clocking_ctl.enb(14)
  verilogBlackBox.io.ilro_enb_15 := io.clocking_ctl.enb(15)
  verilogBlackBox.io.ilro_enb_16 := io.clocking_ctl.enb(16)
  verilogBlackBox.io.ilro_enb_17 := io.clocking_ctl.enb(17)
  verilogBlackBox.io.ilro_enb_18 := io.clocking_ctl.enb(18)
  verilogBlackBox.io.ilro_enb_19 := io.clocking_ctl.enb(19)
  verilogBlackBox.io.ilro_enb_20 := io.clocking_ctl.enb(20)
  verilogBlackBox.io.ilro_enb_21 := io.clocking_ctl.enb(21)
  verilogBlackBox.io.ilro_enb_22 := io.clocking_ctl.enb(22)
  verilogBlackBox.io.ilro_enb_23 := io.clocking_ctl.enb(23)
  verilogBlackBox.io.ilro_enb_24 := io.clocking_ctl.enb(24)
  verilogBlackBox.io.ilro_enb_25 := io.clocking_ctl.enb(25)
  verilogBlackBox.io.ilro_enb_26 := io.clocking_ctl.enb(26)
  verilogBlackBox.io.ilro_enb_27 := io.clocking_ctl.enb(27)
  verilogBlackBox.io.ilro_enb_28 := io.clocking_ctl.enb(28)
  verilogBlackBox.io.ilro_enb_29 := io.clocking_ctl.enb(29)
  verilogBlackBox.io.ilro_enb_30 := io.clocking_ctl.enb(30)
  verilogBlackBox.io.ilro_enb_31 := io.clocking_ctl.enb(31)
  verilogBlackBox.io.ilro_enb_32 := io.clocking_ctl.enb(32)
  verilogBlackBox.io.ilro_enb_33 := io.clocking_ctl.enb(33)
  verilogBlackBox.io.ilro_enb_34 := io.clocking_ctl.enb(34)
  verilogBlackBox.io.ilro_enb_35 := io.clocking_ctl.enb(35)
  verilogBlackBox.io.ilro_enb_36 := io.clocking_ctl.enb(36)
  verilogBlackBox.io.ilro_enb_37 := io.clocking_ctl.enb(37)
  verilogBlackBox.io.ilro_enb_38 := io.clocking_ctl.enb(38)
  verilogBlackBox.io.ilro_enb_39 := io.clocking_ctl.enb(39)
  verilogBlackBox.io.ilro_enb_40 := io.clocking_ctl.enb(40)
  verilogBlackBox.io.ilro_enb_41 := io.clocking_ctl.enb(41)
  verilogBlackBox.io.ilro_enb_42 := io.clocking_ctl.enb(42)
  verilogBlackBox.io.ilro_enb_43 := io.clocking_ctl.enb(43)
  verilogBlackBox.io.ilro_enb_44 := io.clocking_ctl.enb(44)
  verilogBlackBox.io.ilro_enb_45 := io.clocking_ctl.enb(45)
  verilogBlackBox.io.ilro_enb_46 := io.clocking_ctl.enb(46)
  verilogBlackBox.io.ilro_enb_47 := io.clocking_ctl.enb(47)
  verilogBlackBox.io.ilro_enb_48 := io.clocking_ctl.enb(48)
  verilogBlackBox.io.ilro_enb_49 := io.clocking_ctl.enb(49)
  verilogBlackBox.io.ilro_enb_50 := io.clocking_ctl.enb(50)
  verilogBlackBox.io.ilro_enb_51 := io.clocking_ctl.enb(51)
  verilogBlackBox.io.ilro_enb_52 := io.clocking_ctl.enb(52)
  verilogBlackBox.io.ilro_enb_53 := io.clocking_ctl.enb(53)
  verilogBlackBox.io.ilro_enb_54 := io.clocking_ctl.enb(54)
  verilogBlackBox.io.ilro_enb_55 := io.clocking_ctl.enb(55)
  verilogBlackBox.io.ilro_enb_56 := io.clocking_ctl.enb(56)
  verilogBlackBox.io.ilro_enb_57 := io.clocking_ctl.enb(57)
  verilogBlackBox.io.ilro_enb_58 := io.clocking_ctl.enb(58)
  verilogBlackBox.io.ilro_enb_59 := io.clocking_ctl.enb(59)
  verilogBlackBox.io.ilro_enb_60 := io.clocking_ctl.enb(60)
  verilogBlackBox.io.ilro_enb_61 := io.clocking_ctl.enb(61)
  verilogBlackBox.io.ilro_enb_62 := io.clocking_ctl.enb(62)
  verilogBlackBox.io.ilro_enb_63 := io.clocking_ctl.enb(63)

  // val ctr = withClockAndReset(io.injp.asClock, !io.resetb) { RegInit(0.U((log2Ceil(Phy.SerdesRatio) - 1).W)) }
  // ctr := ctr + 1.U

  // val divClock = withClockAndReset(io.injp.asClock, !io.resetb) { RegInit(false.B) }
  // when (ctr === 0.U) {
  //   divClock := !divClock
  // }

  // val shiftReg = withClockAndReset(io.injp.asClock, !io.resetb) { RegInit(0.U(Phy.SerdesRatio.W)) }
  // shiftReg := shiftReg >> 1.U
  // when (ctr === 0.U && !divClock) {
  //   shiftReg := io.din.asTypeOf(shiftReg)
  // }

  // io.divclk := divClock.asClock
  // io.dout := shiftReg(0)

  // io.driver_ctl <> 0.U.asTypeOf(io.driver_ctl)
  // io.clocking_ctl <> 0.U.asTypeOf(io.clocking_ctl)
}

class VerilogTxLaneIO extends Bundle {
  val injp = Input(Bool())
  val injm = Input(Bool())
  val in = Input(Bool())
  val din_0 = Input(Bool())
  val din_1 = Input(Bool())
  val din_2 = Input(Bool())
  val din_3 = Input(Bool())
  val din_4 = Input(Bool())
  val din_5 = Input(Bool())
  val din_6 = Input(Bool())
  val din_7 = Input(Bool())
  val din_8 = Input(Bool())
  val din_9 = Input(Bool())
  val din_10 = Input(Bool())
  val din_11 = Input(Bool())
  val din_12 = Input(Bool())
  val din_13 = Input(Bool())
  val din_14 = Input(Bool())
  val din_15 = Input(Bool())
  val dout = Output(Bool())
  val divclk = Output(Clock())
  val resetb = Input(Bool())
  val pu_ctl_0 = Input(Bool())
  val pu_ctl_1 = Input(Bool())
  val pu_ctl_2 = Input(Bool())
  val pu_ctl_3 = Input(Bool())
  val pu_ctl_4 = Input(Bool())
  val pu_ctl_5 = Input(Bool())
  val pu_ctl_6 = Input(Bool())
  val pu_ctl_7 = Input(Bool())
  val pu_ctl_8 = Input(Bool())
  val pu_ctl_9 = Input(Bool())
  val pu_ctl_10 = Input(Bool())
  val pu_ctl_11 = Input(Bool())
  val pu_ctl_12 = Input(Bool())
  val pu_ctl_13 = Input(Bool())
  val pu_ctl_14 = Input(Bool())
  val pu_ctl_15 = Input(Bool())
  val pu_ctl_16 = Input(Bool())
  val pu_ctl_17 = Input(Bool())
  val pu_ctl_18 = Input(Bool())
  val pu_ctl_19 = Input(Bool())
  val pu_ctl_20 = Input(Bool())
  val pu_ctl_21 = Input(Bool())
  val pu_ctl_22 = Input(Bool())
  val pu_ctl_23 = Input(Bool())
  val pu_ctl_24 = Input(Bool())
  val pu_ctl_25 = Input(Bool())
  val pu_ctl_26 = Input(Bool())
  val pu_ctl_27 = Input(Bool())
  val pu_ctl_28 = Input(Bool())
  val pu_ctl_29 = Input(Bool())
  val pu_ctl_30 = Input(Bool())
  val pu_ctl_31 = Input(Bool())
  val pu_ctl_32 = Input(Bool())
  val pu_ctl_33 = Input(Bool())
  val pu_ctl_34 = Input(Bool())
  val pu_ctl_35 = Input(Bool())
  val pu_ctl_36 = Input(Bool())
  val pu_ctl_37 = Input(Bool())
  val pu_ctl_38 = Input(Bool())
  val pu_ctl_39 = Input(Bool())
  val pu_ctl_40 = Input(Bool())
  val pu_ctl_41 = Input(Bool())
  val pu_ctl_42 = Input(Bool())
  val pu_ctl_43 = Input(Bool())
  val pu_ctl_44 = Input(Bool())
  val pu_ctl_45 = Input(Bool())
  val pu_ctl_46 = Input(Bool())
  val pu_ctl_47 = Input(Bool())
  val pd_ctlb_0 = Input(Bool())
  val pd_ctlb_1 = Input(Bool())
  val pd_ctlb_2 = Input(Bool())
  val pd_ctlb_3 = Input(Bool())
  val pd_ctlb_4 = Input(Bool())
  val pd_ctlb_5 = Input(Bool())
  val pd_ctlb_6 = Input(Bool())
  val pd_ctlb_7 = Input(Bool())
  val pd_ctlb_8 = Input(Bool())
  val pd_ctlb_9 = Input(Bool())
  val pd_ctlb_10 = Input(Bool())
  val pd_ctlb_11 = Input(Bool())
  val pd_ctlb_12 = Input(Bool())
  val pd_ctlb_13 = Input(Bool())
  val pd_ctlb_14 = Input(Bool())
  val pd_ctlb_15 = Input(Bool())
  val pd_ctlb_16 = Input(Bool())
  val pd_ctlb_17 = Input(Bool())
  val pd_ctlb_18 = Input(Bool())
  val pd_ctlb_19 = Input(Bool())
  val pd_ctlb_20 = Input(Bool())
  val pd_ctlb_21 = Input(Bool())
  val pd_ctlb_22 = Input(Bool())
  val pd_ctlb_23 = Input(Bool())
  val pd_ctlb_24 = Input(Bool())
  val pd_ctlb_25 = Input(Bool())
  val pd_ctlb_26 = Input(Bool())
  val pd_ctlb_27 = Input(Bool())
  val pd_ctlb_28 = Input(Bool())
  val pd_ctlb_29 = Input(Bool())
  val pd_ctlb_30 = Input(Bool())
  val pd_ctlb_31 = Input(Bool())
  val pd_ctlb_32 = Input(Bool())
  val pd_ctlb_33 = Input(Bool())
  val pd_ctlb_34 = Input(Bool())
  val pd_ctlb_35 = Input(Bool())
  val pd_ctlb_36 = Input(Bool())
  val pd_ctlb_37 = Input(Bool())
  val pd_ctlb_38 = Input(Bool())
  val pd_ctlb_39 = Input(Bool())
  val pd_ctlb_40 = Input(Bool())
  val pd_ctlb_41 = Input(Bool())
  val pd_ctlb_42 = Input(Bool())
  val pd_ctlb_43 = Input(Bool())
  val pd_ctlb_44 = Input(Bool())
  val pd_ctlb_45 = Input(Bool())
  val pd_ctlb_46 = Input(Bool())
  val pd_ctlb_47 = Input(Bool())
  val en = Input(Bool()) 
  val en_b = Input(Bool()) 
  val band_ctrl_0 = Input(Bool())
  val band_ctrl_1 = Input(Bool())
  val band_ctrlb_0 = Input(Bool())
  val band_ctrlb_1 = Input(Bool())
  val band_sel_0 = Input(Bool())
  val band_sel_1 = Input(Bool())
  val band_selb_0 = Input(Bool())
  val band_selb_1 = Input(Bool())
  val mix_en = Input(Bits(16.W))
  val mix_enb = Input(Bits(16.W))
  val mux_en = Input(Bits(8.W))
  val mux_enb = Input(Bits(8.W))
  val ph_sel_0 = Input(Bool())
  val ph_sel_1 = Input(Bool())
  val ph_selb_0 = Input(Bool())
  val ph_selb_1 = Input(Bool())
  val ilro_en_0 = Input(Bool())
  val ilro_en_1 = Input(Bool())
  val ilro_en_2 = Input(Bool())
  val ilro_en_3 = Input(Bool())
  val ilro_en_4 = Input(Bool())
  val ilro_en_5 = Input(Bool())
  val ilro_en_6 = Input(Bool())
  val ilro_en_7 = Input(Bool())
  val ilro_en_8 = Input(Bool())
  val ilro_en_9 = Input(Bool())
  val ilro_en_10 = Input(Bool())
  val ilro_en_11 = Input(Bool())
  val ilro_en_12 = Input(Bool())
  val ilro_en_13 = Input(Bool())
  val ilro_en_14 = Input(Bool())
  val ilro_en_15 = Input(Bool())
  val ilro_en_16 = Input(Bool())
  val ilro_en_17 = Input(Bool())
  val ilro_en_18 = Input(Bool())
  val ilro_en_19 = Input(Bool())
  val ilro_en_20 = Input(Bool())
  val ilro_en_21 = Input(Bool())
  val ilro_en_22 = Input(Bool())
  val ilro_en_23 = Input(Bool())
  val ilro_en_24 = Input(Bool())
  val ilro_en_25 = Input(Bool())
  val ilro_en_26 = Input(Bool())
  val ilro_en_27 = Input(Bool())
  val ilro_en_28 = Input(Bool())
  val ilro_en_29 = Input(Bool())
  val ilro_en_30 = Input(Bool())
  val ilro_en_31 = Input(Bool())
  val ilro_en_32 = Input(Bool())
  val ilro_en_33 = Input(Bool())
  val ilro_en_34 = Input(Bool())
  val ilro_en_35 = Input(Bool())
  val ilro_en_36 = Input(Bool())
  val ilro_en_37 = Input(Bool())
  val ilro_en_38 = Input(Bool())
  val ilro_en_39 = Input(Bool())
  val ilro_en_40 = Input(Bool())
  val ilro_en_41 = Input(Bool())
  val ilro_en_42 = Input(Bool())
  val ilro_en_43 = Input(Bool())
  val ilro_en_44 = Input(Bool())
  val ilro_en_45 = Input(Bool())
  val ilro_en_46 = Input(Bool())
  val ilro_en_47 = Input(Bool())
  val ilro_en_48 = Input(Bool())
  val ilro_en_49 = Input(Bool())
  val ilro_en_50 = Input(Bool())
  val ilro_en_51 = Input(Bool())
  val ilro_en_52 = Input(Bool())
  val ilro_en_53 = Input(Bool())
  val ilro_en_54 = Input(Bool())
  val ilro_en_55 = Input(Bool())
  val ilro_en_56 = Input(Bool())
  val ilro_en_57 = Input(Bool())
  val ilro_en_58 = Input(Bool())
  val ilro_en_59 = Input(Bool())
  val ilro_en_60 = Input(Bool())
  val ilro_en_61 = Input(Bool())
  val ilro_en_62 = Input(Bool())
  val ilro_en_63 = Input(Bool())
  val ilro_en_64 = Input(Bool())
  val ilro_enb_0 = Input(Bool())
  val ilro_enb_1 = Input(Bool())
  val ilro_enb_2 = Input(Bool())
  val ilro_enb_3 = Input(Bool())
  val ilro_enb_4 = Input(Bool())
  val ilro_enb_5 = Input(Bool())
  val ilro_enb_6 = Input(Bool())
  val ilro_enb_7 = Input(Bool())
  val ilro_enb_8 = Input(Bool())
  val ilro_enb_9 = Input(Bool())
  val ilro_enb_10 = Input(Bool())
  val ilro_enb_11 = Input(Bool())
  val ilro_enb_12 = Input(Bool())
  val ilro_enb_13 = Input(Bool())
  val ilro_enb_14 = Input(Bool())
  val ilro_enb_15 = Input(Bool())
  val ilro_enb_16 = Input(Bool())
  val ilro_enb_17 = Input(Bool())
  val ilro_enb_18 = Input(Bool())
  val ilro_enb_19 = Input(Bool())
  val ilro_enb_20 = Input(Bool())
  val ilro_enb_21 = Input(Bool())
  val ilro_enb_22 = Input(Bool())
  val ilro_enb_23 = Input(Bool())
  val ilro_enb_24 = Input(Bool())
  val ilro_enb_25 = Input(Bool())
  val ilro_enb_26 = Input(Bool())
  val ilro_enb_27 = Input(Bool())
  val ilro_enb_28 = Input(Bool())
  val ilro_enb_29 = Input(Bool())
  val ilro_enb_30 = Input(Bool())
  val ilro_enb_31 = Input(Bool())
  val ilro_enb_32 = Input(Bool())
  val ilro_enb_33 = Input(Bool())
  val ilro_enb_34 = Input(Bool())
  val ilro_enb_35 = Input(Bool())
  val ilro_enb_36 = Input(Bool())
  val ilro_enb_37 = Input(Bool())
  val ilro_enb_38 = Input(Bool())
  val ilro_enb_39 = Input(Bool())
  val ilro_enb_40 = Input(Bool())
  val ilro_enb_41 = Input(Bool())
  val ilro_enb_42 = Input(Bool())
  val ilro_enb_43 = Input(Bool())
  val ilro_enb_44 = Input(Bool())
  val ilro_enb_45 = Input(Bool())
  val ilro_enb_46 = Input(Bool())
  val ilro_enb_47 = Input(Bool())
  val ilro_enb_48 = Input(Bool())
  val ilro_enb_49 = Input(Bool())
  val ilro_enb_50 = Input(Bool())
  val ilro_enb_51 = Input(Bool())
  val ilro_enb_52 = Input(Bool())
  val ilro_enb_53 = Input(Bool())
  val ilro_enb_54 = Input(Bool())
  val ilro_enb_55 = Input(Bool())
  val ilro_enb_56 = Input(Bool())
  val ilro_enb_57 = Input(Bool())
  val ilro_enb_58 = Input(Bool())
  val ilro_enb_59 = Input(Bool())
  val ilro_enb_60 = Input(Bool())
  val ilro_enb_61 = Input(Bool())
  val ilro_enb_62 = Input(Bool())
  val ilro_enb_63 = Input(Bool())
  val ilro_enb_64 = Input(Bool())
}

class VerilogTxLane extends BlackBox {
  val io = IO(new VerilogTxLaneIO)

  override val desiredName = "TX_data_lane"
}

class TxClkIO extends Bundle {
  val injp = Input(Bool())
  val injm = Input(Bool())
  val in = Input(Bool())
  val txckp = Output(Bool())
  val txckn = Output(Bool())
  val driver_ctl = Vec(2, new DriverControlIO)
  val en = Input(Bits(64.W))
  val enb = Input(Bits(64.W))
}

class TxClk extends RawModule {
  val io = IO(new TxClkIO)

  val verilogBlackBox = Module(new VerilogTxClk)
  verilogBlackBox.io.injp := io.injp
  verilogBlackBox.io.injm := io.injm
  verilogBlackBox.io.in := io.in
  io.txckp := verilogBlackBox.io.txckp
  io.txckn := verilogBlackBox.io.txckn
  verilogBlackBox.io.pu_ctl_p_0  := io.driver_ctl(0).pu_ctl.pu_ctl_0
  verilogBlackBox.io.pu_ctl_p_1  := io.driver_ctl(0).pu_ctl.pu_ctl_1
  verilogBlackBox.io.pu_ctl_p_2  := io.driver_ctl(0).pu_ctl.pu_ctl_2
  verilogBlackBox.io.pu_ctl_p_3  := io.driver_ctl(0).pu_ctl.pu_ctl_3
  verilogBlackBox.io.pu_ctl_p_4  := io.driver_ctl(0).pu_ctl.pu_ctl_4
  verilogBlackBox.io.pu_ctl_p_5  := io.driver_ctl(0).pu_ctl.pu_ctl_5
  verilogBlackBox.io.pu_ctl_p_6  := io.driver_ctl(0).pu_ctl.pu_ctl_6
  verilogBlackBox.io.pu_ctl_p_7  := io.driver_ctl(0).pu_ctl.pu_ctl_7
  verilogBlackBox.io.pu_ctl_p_8  := io.driver_ctl(0).pu_ctl.pu_ctl_8
  verilogBlackBox.io.pu_ctl_p_9  := io.driver_ctl(0).pu_ctl.pu_ctl_9
  verilogBlackBox.io.pu_ctl_p_10 := io.driver_ctl(0).pu_ctl.pu_ctl_10
  verilogBlackBox.io.pu_ctl_p_11 := io.driver_ctl(0).pu_ctl.pu_ctl_11
  verilogBlackBox.io.pu_ctl_p_12 := io.driver_ctl(0).pu_ctl.pu_ctl_12
  verilogBlackBox.io.pu_ctl_p_13 := io.driver_ctl(0).pu_ctl.pu_ctl_13
  verilogBlackBox.io.pu_ctl_p_14 := io.driver_ctl(0).pu_ctl.pu_ctl_14
  verilogBlackBox.io.pu_ctl_p_15 := io.driver_ctl(0).pu_ctl.pu_ctl_15
  verilogBlackBox.io.pu_ctl_p_16 := io.driver_ctl(0).pu_ctl.pu_ctl_16
  verilogBlackBox.io.pu_ctl_p_17 := io.driver_ctl(0).pu_ctl.pu_ctl_17
  verilogBlackBox.io.pu_ctl_p_18 := io.driver_ctl(0).pu_ctl.pu_ctl_18
  verilogBlackBox.io.pu_ctl_p_19 := io.driver_ctl(0).pu_ctl.pu_ctl_19
  verilogBlackBox.io.pu_ctl_p_20 := io.driver_ctl(0).pu_ctl.pu_ctl_20
  verilogBlackBox.io.pu_ctl_p_21 := io.driver_ctl(0).pu_ctl.pu_ctl_21
  verilogBlackBox.io.pu_ctl_p_22 := io.driver_ctl(0).pu_ctl.pu_ctl_22
  verilogBlackBox.io.pu_ctl_p_23 := io.driver_ctl(0).pu_ctl.pu_ctl_23
  verilogBlackBox.io.pu_ctl_p_24 := io.driver_ctl(0).pu_ctl.pu_ctl_24
  verilogBlackBox.io.pu_ctl_p_25 := io.driver_ctl(0).pu_ctl.pu_ctl_25
  verilogBlackBox.io.pu_ctl_p_26 := io.driver_ctl(0).pu_ctl.pu_ctl_26
  verilogBlackBox.io.pu_ctl_p_27 := io.driver_ctl(0).pu_ctl.pu_ctl_27
  verilogBlackBox.io.pu_ctl_p_28 := io.driver_ctl(0).pu_ctl.pu_ctl_28
  verilogBlackBox.io.pu_ctl_p_29 := io.driver_ctl(0).pu_ctl.pu_ctl_29
  verilogBlackBox.io.pu_ctl_p_30 := io.driver_ctl(0).pu_ctl.pu_ctl_30
  verilogBlackBox.io.pu_ctl_p_31 := io.driver_ctl(0).pu_ctl.pu_ctl_31
  verilogBlackBox.io.pu_ctl_p_32 := io.driver_ctl(0).pu_ctl.pu_ctl_32
  verilogBlackBox.io.pu_ctl_p_33 := io.driver_ctl(0).pu_ctl.pu_ctl_33
  verilogBlackBox.io.pu_ctl_p_34 := io.driver_ctl(0).pu_ctl.pu_ctl_34
  verilogBlackBox.io.pu_ctl_p_35 := io.driver_ctl(0).pu_ctl.pu_ctl_35
  verilogBlackBox.io.pu_ctl_p_36 := io.driver_ctl(0).pu_ctl.pu_ctl_36
  verilogBlackBox.io.pu_ctl_p_37 := io.driver_ctl(0).pu_ctl.pu_ctl_37
  verilogBlackBox.io.pu_ctl_p_38 := io.driver_ctl(0).pu_ctl.pu_ctl_38
  verilogBlackBox.io.pu_ctl_p_39 := io.driver_ctl(0).pu_ctl.pu_ctl_39
  verilogBlackBox.io.pu_ctl_p_40 := io.driver_ctl(0).pu_ctl.pu_ctl_40
  verilogBlackBox.io.pu_ctl_p_41 := io.driver_ctl(0).pu_ctl.pu_ctl_41
  verilogBlackBox.io.pu_ctl_p_42 := io.driver_ctl(0).pu_ctl.pu_ctl_42
  verilogBlackBox.io.pu_ctl_p_43 := io.driver_ctl(0).pu_ctl.pu_ctl_43
  verilogBlackBox.io.pu_ctl_p_44 := io.driver_ctl(0).pu_ctl.pu_ctl_44
  verilogBlackBox.io.pu_ctl_p_45 := io.driver_ctl(0).pu_ctl.pu_ctl_45
  verilogBlackBox.io.pu_ctl_p_46 := io.driver_ctl(0).pu_ctl.pu_ctl_46
  verilogBlackBox.io.pu_ctl_p_47 := io.driver_ctl(0).pu_ctl.pu_ctl_47
  verilogBlackBox.io.pd_ctlb_p_0  := io.driver_ctl(0).pd_ctlb.pd_ctlb_0
  verilogBlackBox.io.pd_ctlb_p_1  := io.driver_ctl(0).pd_ctlb.pd_ctlb_1
  verilogBlackBox.io.pd_ctlb_p_2  := io.driver_ctl(0).pd_ctlb.pd_ctlb_2
  verilogBlackBox.io.pd_ctlb_p_3  := io.driver_ctl(0).pd_ctlb.pd_ctlb_3
  verilogBlackBox.io.pd_ctlb_p_4  := io.driver_ctl(0).pd_ctlb.pd_ctlb_4
  verilogBlackBox.io.pd_ctlb_p_5  := io.driver_ctl(0).pd_ctlb.pd_ctlb_5
  verilogBlackBox.io.pd_ctlb_p_6  := io.driver_ctl(0).pd_ctlb.pd_ctlb_6
  verilogBlackBox.io.pd_ctlb_p_7  := io.driver_ctl(0).pd_ctlb.pd_ctlb_7
  verilogBlackBox.io.pd_ctlb_p_8  := io.driver_ctl(0).pd_ctlb.pd_ctlb_8
  verilogBlackBox.io.pd_ctlb_p_9  := io.driver_ctl(0).pd_ctlb.pd_ctlb_9
  verilogBlackBox.io.pd_ctlb_p_10 := io.driver_ctl(0).pd_ctlb.pd_ctlb_10
  verilogBlackBox.io.pd_ctlb_p_11 := io.driver_ctl(0).pd_ctlb.pd_ctlb_11
  verilogBlackBox.io.pd_ctlb_p_12 := io.driver_ctl(0).pd_ctlb.pd_ctlb_12
  verilogBlackBox.io.pd_ctlb_p_13 := io.driver_ctl(0).pd_ctlb.pd_ctlb_13
  verilogBlackBox.io.pd_ctlb_p_14 := io.driver_ctl(0).pd_ctlb.pd_ctlb_14
  verilogBlackBox.io.pd_ctlb_p_15 := io.driver_ctl(0).pd_ctlb.pd_ctlb_15
  verilogBlackBox.io.pd_ctlb_p_16 := io.driver_ctl(0).pd_ctlb.pd_ctlb_16
  verilogBlackBox.io.pd_ctlb_p_17 := io.driver_ctl(0).pd_ctlb.pd_ctlb_17
  verilogBlackBox.io.pd_ctlb_p_18 := io.driver_ctl(0).pd_ctlb.pd_ctlb_18
  verilogBlackBox.io.pd_ctlb_p_19 := io.driver_ctl(0).pd_ctlb.pd_ctlb_19
  verilogBlackBox.io.pd_ctlb_p_20 := io.driver_ctl(0).pd_ctlb.pd_ctlb_20
  verilogBlackBox.io.pd_ctlb_p_21 := io.driver_ctl(0).pd_ctlb.pd_ctlb_21
  verilogBlackBox.io.pd_ctlb_p_22 := io.driver_ctl(0).pd_ctlb.pd_ctlb_22
  verilogBlackBox.io.pd_ctlb_p_23 := io.driver_ctl(0).pd_ctlb.pd_ctlb_23
  verilogBlackBox.io.pd_ctlb_p_24 := io.driver_ctl(0).pd_ctlb.pd_ctlb_24
  verilogBlackBox.io.pd_ctlb_p_25 := io.driver_ctl(0).pd_ctlb.pd_ctlb_25
  verilogBlackBox.io.pd_ctlb_p_26 := io.driver_ctl(0).pd_ctlb.pd_ctlb_26
  verilogBlackBox.io.pd_ctlb_p_27 := io.driver_ctl(0).pd_ctlb.pd_ctlb_27
  verilogBlackBox.io.pd_ctlb_p_28 := io.driver_ctl(0).pd_ctlb.pd_ctlb_28
  verilogBlackBox.io.pd_ctlb_p_29 := io.driver_ctl(0).pd_ctlb.pd_ctlb_29
  verilogBlackBox.io.pd_ctlb_p_30 := io.driver_ctl(0).pd_ctlb.pd_ctlb_30
  verilogBlackBox.io.pd_ctlb_p_31 := io.driver_ctl(0).pd_ctlb.pd_ctlb_31
  verilogBlackBox.io.pd_ctlb_p_32 := io.driver_ctl(0).pd_ctlb.pd_ctlb_32
  verilogBlackBox.io.pd_ctlb_p_33 := io.driver_ctl(0).pd_ctlb.pd_ctlb_33
  verilogBlackBox.io.pd_ctlb_p_34 := io.driver_ctl(0).pd_ctlb.pd_ctlb_34
  verilogBlackBox.io.pd_ctlb_p_35 := io.driver_ctl(0).pd_ctlb.pd_ctlb_35
  verilogBlackBox.io.pd_ctlb_p_36 := io.driver_ctl(0).pd_ctlb.pd_ctlb_36
  verilogBlackBox.io.pd_ctlb_p_37 := io.driver_ctl(0).pd_ctlb.pd_ctlb_37
  verilogBlackBox.io.pd_ctlb_p_38 := io.driver_ctl(0).pd_ctlb.pd_ctlb_38
  verilogBlackBox.io.pd_ctlb_p_39 := io.driver_ctl(0).pd_ctlb.pd_ctlb_39
  verilogBlackBox.io.pd_ctlb_p_40 := io.driver_ctl(0).pd_ctlb.pd_ctlb_40
  verilogBlackBox.io.pd_ctlb_p_41 := io.driver_ctl(0).pd_ctlb.pd_ctlb_41
  verilogBlackBox.io.pd_ctlb_p_42 := io.driver_ctl(0).pd_ctlb.pd_ctlb_42
  verilogBlackBox.io.pd_ctlb_p_43 := io.driver_ctl(0).pd_ctlb.pd_ctlb_43
  verilogBlackBox.io.pd_ctlb_p_44 := io.driver_ctl(0).pd_ctlb.pd_ctlb_44
  verilogBlackBox.io.pd_ctlb_p_45 := io.driver_ctl(0).pd_ctlb.pd_ctlb_45
  verilogBlackBox.io.pd_ctlb_p_46 := io.driver_ctl(0).pd_ctlb.pd_ctlb_46
  verilogBlackBox.io.pd_ctlb_p_47 := io.driver_ctl(0).pd_ctlb.pd_ctlb_47
  verilogBlackBox.io.en_p := io.driver_ctl(0).en
  verilogBlackBox.io.en_b_p := io.driver_ctl(0).en_b
  verilogBlackBox.io.pu_ctl_n_0  := io.driver_ctl(1).pu_ctl.pu_ctl_0
  verilogBlackBox.io.pu_ctl_n_1  := io.driver_ctl(1).pu_ctl.pu_ctl_1
  verilogBlackBox.io.pu_ctl_n_2  := io.driver_ctl(1).pu_ctl.pu_ctl_2
  verilogBlackBox.io.pu_ctl_n_3  := io.driver_ctl(1).pu_ctl.pu_ctl_3
  verilogBlackBox.io.pu_ctl_n_4  := io.driver_ctl(1).pu_ctl.pu_ctl_4
  verilogBlackBox.io.pu_ctl_n_5  := io.driver_ctl(1).pu_ctl.pu_ctl_5
  verilogBlackBox.io.pu_ctl_n_6  := io.driver_ctl(1).pu_ctl.pu_ctl_6
  verilogBlackBox.io.pu_ctl_n_7  := io.driver_ctl(1).pu_ctl.pu_ctl_7
  verilogBlackBox.io.pu_ctl_n_8  := io.driver_ctl(1).pu_ctl.pu_ctl_8
  verilogBlackBox.io.pu_ctl_n_9  := io.driver_ctl(1).pu_ctl.pu_ctl_9
  verilogBlackBox.io.pu_ctl_n_10 := io.driver_ctl(1).pu_ctl.pu_ctl_10
  verilogBlackBox.io.pu_ctl_n_11 := io.driver_ctl(1).pu_ctl.pu_ctl_11
  verilogBlackBox.io.pu_ctl_n_12 := io.driver_ctl(1).pu_ctl.pu_ctl_12
  verilogBlackBox.io.pu_ctl_n_13 := io.driver_ctl(1).pu_ctl.pu_ctl_13
  verilogBlackBox.io.pu_ctl_n_14 := io.driver_ctl(1).pu_ctl.pu_ctl_14
  verilogBlackBox.io.pu_ctl_n_15 := io.driver_ctl(1).pu_ctl.pu_ctl_15
  verilogBlackBox.io.pu_ctl_n_16 := io.driver_ctl(1).pu_ctl.pu_ctl_16
  verilogBlackBox.io.pu_ctl_n_17 := io.driver_ctl(1).pu_ctl.pu_ctl_17
  verilogBlackBox.io.pu_ctl_n_18 := io.driver_ctl(1).pu_ctl.pu_ctl_18
  verilogBlackBox.io.pu_ctl_n_19 := io.driver_ctl(1).pu_ctl.pu_ctl_19
  verilogBlackBox.io.pu_ctl_n_20 := io.driver_ctl(1).pu_ctl.pu_ctl_20
  verilogBlackBox.io.pu_ctl_n_21 := io.driver_ctl(1).pu_ctl.pu_ctl_21
  verilogBlackBox.io.pu_ctl_n_22 := io.driver_ctl(1).pu_ctl.pu_ctl_22
  verilogBlackBox.io.pu_ctl_n_23 := io.driver_ctl(1).pu_ctl.pu_ctl_23
  verilogBlackBox.io.pu_ctl_n_24 := io.driver_ctl(1).pu_ctl.pu_ctl_24
  verilogBlackBox.io.pu_ctl_n_25 := io.driver_ctl(1).pu_ctl.pu_ctl_25
  verilogBlackBox.io.pu_ctl_n_26 := io.driver_ctl(1).pu_ctl.pu_ctl_26
  verilogBlackBox.io.pu_ctl_n_27 := io.driver_ctl(1).pu_ctl.pu_ctl_27
  verilogBlackBox.io.pu_ctl_n_28 := io.driver_ctl(1).pu_ctl.pu_ctl_28
  verilogBlackBox.io.pu_ctl_n_29 := io.driver_ctl(1).pu_ctl.pu_ctl_29
  verilogBlackBox.io.pu_ctl_n_30 := io.driver_ctl(1).pu_ctl.pu_ctl_30
  verilogBlackBox.io.pu_ctl_n_31 := io.driver_ctl(1).pu_ctl.pu_ctl_31
  verilogBlackBox.io.pu_ctl_n_32 := io.driver_ctl(1).pu_ctl.pu_ctl_32
  verilogBlackBox.io.pu_ctl_n_33 := io.driver_ctl(1).pu_ctl.pu_ctl_33
  verilogBlackBox.io.pu_ctl_n_34 := io.driver_ctl(1).pu_ctl.pu_ctl_34
  verilogBlackBox.io.pu_ctl_n_35 := io.driver_ctl(1).pu_ctl.pu_ctl_35
  verilogBlackBox.io.pu_ctl_n_36 := io.driver_ctl(1).pu_ctl.pu_ctl_36
  verilogBlackBox.io.pu_ctl_n_37 := io.driver_ctl(1).pu_ctl.pu_ctl_37
  verilogBlackBox.io.pu_ctl_n_38 := io.driver_ctl(1).pu_ctl.pu_ctl_38
  verilogBlackBox.io.pu_ctl_n_39 := io.driver_ctl(1).pu_ctl.pu_ctl_39
  verilogBlackBox.io.pu_ctl_n_40 := io.driver_ctl(1).pu_ctl.pu_ctl_40
  verilogBlackBox.io.pu_ctl_n_41 := io.driver_ctl(1).pu_ctl.pu_ctl_41
  verilogBlackBox.io.pu_ctl_n_42 := io.driver_ctl(1).pu_ctl.pu_ctl_42
  verilogBlackBox.io.pu_ctl_n_43 := io.driver_ctl(1).pu_ctl.pu_ctl_43
  verilogBlackBox.io.pu_ctl_n_44 := io.driver_ctl(1).pu_ctl.pu_ctl_44
  verilogBlackBox.io.pu_ctl_n_45 := io.driver_ctl(1).pu_ctl.pu_ctl_45
  verilogBlackBox.io.pu_ctl_n_46 := io.driver_ctl(1).pu_ctl.pu_ctl_46
  verilogBlackBox.io.pu_ctl_n_47 := io.driver_ctl(1).pu_ctl.pu_ctl_47
  verilogBlackBox.io.pd_ctlb_n_0  := io.driver_ctl(1).pd_ctlb.pd_ctlb_0
  verilogBlackBox.io.pd_ctlb_n_1  := io.driver_ctl(1).pd_ctlb.pd_ctlb_1
  verilogBlackBox.io.pd_ctlb_n_2  := io.driver_ctl(1).pd_ctlb.pd_ctlb_2
  verilogBlackBox.io.pd_ctlb_n_3  := io.driver_ctl(1).pd_ctlb.pd_ctlb_3
  verilogBlackBox.io.pd_ctlb_n_4  := io.driver_ctl(1).pd_ctlb.pd_ctlb_4
  verilogBlackBox.io.pd_ctlb_n_5  := io.driver_ctl(1).pd_ctlb.pd_ctlb_5
  verilogBlackBox.io.pd_ctlb_n_6  := io.driver_ctl(1).pd_ctlb.pd_ctlb_6
  verilogBlackBox.io.pd_ctlb_n_7  := io.driver_ctl(1).pd_ctlb.pd_ctlb_7
  verilogBlackBox.io.pd_ctlb_n_8  := io.driver_ctl(1).pd_ctlb.pd_ctlb_8
  verilogBlackBox.io.pd_ctlb_n_9  := io.driver_ctl(1).pd_ctlb.pd_ctlb_9
  verilogBlackBox.io.pd_ctlb_n_10 := io.driver_ctl(1).pd_ctlb.pd_ctlb_10
  verilogBlackBox.io.pd_ctlb_n_11 := io.driver_ctl(1).pd_ctlb.pd_ctlb_11
  verilogBlackBox.io.pd_ctlb_n_12 := io.driver_ctl(1).pd_ctlb.pd_ctlb_12
  verilogBlackBox.io.pd_ctlb_n_13 := io.driver_ctl(1).pd_ctlb.pd_ctlb_13
  verilogBlackBox.io.pd_ctlb_n_14 := io.driver_ctl(1).pd_ctlb.pd_ctlb_14
  verilogBlackBox.io.pd_ctlb_n_15 := io.driver_ctl(1).pd_ctlb.pd_ctlb_15
  verilogBlackBox.io.pd_ctlb_n_16 := io.driver_ctl(1).pd_ctlb.pd_ctlb_16
  verilogBlackBox.io.pd_ctlb_n_17 := io.driver_ctl(1).pd_ctlb.pd_ctlb_17
  verilogBlackBox.io.pd_ctlb_n_18 := io.driver_ctl(1).pd_ctlb.pd_ctlb_18
  verilogBlackBox.io.pd_ctlb_n_19 := io.driver_ctl(1).pd_ctlb.pd_ctlb_19
  verilogBlackBox.io.pd_ctlb_n_20 := io.driver_ctl(1).pd_ctlb.pd_ctlb_20
  verilogBlackBox.io.pd_ctlb_n_21 := io.driver_ctl(1).pd_ctlb.pd_ctlb_21
  verilogBlackBox.io.pd_ctlb_n_22 := io.driver_ctl(1).pd_ctlb.pd_ctlb_22
  verilogBlackBox.io.pd_ctlb_n_23 := io.driver_ctl(1).pd_ctlb.pd_ctlb_23
  verilogBlackBox.io.pd_ctlb_n_24 := io.driver_ctl(1).pd_ctlb.pd_ctlb_24
  verilogBlackBox.io.pd_ctlb_n_25 := io.driver_ctl(1).pd_ctlb.pd_ctlb_25
  verilogBlackBox.io.pd_ctlb_n_26 := io.driver_ctl(1).pd_ctlb.pd_ctlb_26
  verilogBlackBox.io.pd_ctlb_n_27 := io.driver_ctl(1).pd_ctlb.pd_ctlb_27
  verilogBlackBox.io.pd_ctlb_n_28 := io.driver_ctl(1).pd_ctlb.pd_ctlb_28
  verilogBlackBox.io.pd_ctlb_n_29 := io.driver_ctl(1).pd_ctlb.pd_ctlb_29
  verilogBlackBox.io.pd_ctlb_n_30 := io.driver_ctl(1).pd_ctlb.pd_ctlb_30
  verilogBlackBox.io.pd_ctlb_n_31 := io.driver_ctl(1).pd_ctlb.pd_ctlb_31
  verilogBlackBox.io.pd_ctlb_n_32 := io.driver_ctl(1).pd_ctlb.pd_ctlb_32
  verilogBlackBox.io.pd_ctlb_n_33 := io.driver_ctl(1).pd_ctlb.pd_ctlb_33
  verilogBlackBox.io.pd_ctlb_n_34 := io.driver_ctl(1).pd_ctlb.pd_ctlb_34
  verilogBlackBox.io.pd_ctlb_n_35 := io.driver_ctl(1).pd_ctlb.pd_ctlb_35
  verilogBlackBox.io.pd_ctlb_n_36 := io.driver_ctl(1).pd_ctlb.pd_ctlb_36
  verilogBlackBox.io.pd_ctlb_n_37 := io.driver_ctl(1).pd_ctlb.pd_ctlb_37
  verilogBlackBox.io.pd_ctlb_n_38 := io.driver_ctl(1).pd_ctlb.pd_ctlb_38
  verilogBlackBox.io.pd_ctlb_n_39 := io.driver_ctl(1).pd_ctlb.pd_ctlb_39
  verilogBlackBox.io.pd_ctlb_n_40 := io.driver_ctl(1).pd_ctlb.pd_ctlb_40
  verilogBlackBox.io.pd_ctlb_n_41 := io.driver_ctl(1).pd_ctlb.pd_ctlb_41
  verilogBlackBox.io.pd_ctlb_n_42 := io.driver_ctl(1).pd_ctlb.pd_ctlb_42
  verilogBlackBox.io.pd_ctlb_n_43 := io.driver_ctl(1).pd_ctlb.pd_ctlb_43
  verilogBlackBox.io.pd_ctlb_n_44 := io.driver_ctl(1).pd_ctlb.pd_ctlb_44
  verilogBlackBox.io.pd_ctlb_n_45 := io.driver_ctl(1).pd_ctlb.pd_ctlb_45
  verilogBlackBox.io.pd_ctlb_n_46 := io.driver_ctl(1).pd_ctlb.pd_ctlb_46
  verilogBlackBox.io.pd_ctlb_n_47 := io.driver_ctl(1).pd_ctlb.pd_ctlb_47
  verilogBlackBox.io.en_n := io.driver_ctl(1).en
  verilogBlackBox.io.en_b_n := io.driver_ctl(1).en_b
  verilogBlackBox.io.ilro_en_0 := io.en(0)
  verilogBlackBox.io.ilro_en_1 := io.en(1)
  verilogBlackBox.io.ilro_en_2 := io.en(2)
  verilogBlackBox.io.ilro_en_3 := io.en(3)
  verilogBlackBox.io.ilro_en_4 := io.en(4)
  verilogBlackBox.io.ilro_en_5 := io.en(5)
  verilogBlackBox.io.ilro_en_6 := io.en(6)
  verilogBlackBox.io.ilro_en_7 := io.en(7)
  verilogBlackBox.io.ilro_en_8 := io.en(8)
  verilogBlackBox.io.ilro_en_9 := io.en(9)
  verilogBlackBox.io.ilro_en_10 := io.en(10)
  verilogBlackBox.io.ilro_en_11 := io.en(11)
  verilogBlackBox.io.ilro_en_12 := io.en(12)
  verilogBlackBox.io.ilro_en_13 := io.en(13)
  verilogBlackBox.io.ilro_en_14 := io.en(14)
  verilogBlackBox.io.ilro_en_15 := io.en(15)
  verilogBlackBox.io.ilro_en_16 := io.en(16)
  verilogBlackBox.io.ilro_en_17 := io.en(17)
  verilogBlackBox.io.ilro_en_18 := io.en(18)
  verilogBlackBox.io.ilro_en_19 := io.en(19)
  verilogBlackBox.io.ilro_en_20 := io.en(20)
  verilogBlackBox.io.ilro_en_21 := io.en(21)
  verilogBlackBox.io.ilro_en_22 := io.en(22)
  verilogBlackBox.io.ilro_en_23 := io.en(23)
  verilogBlackBox.io.ilro_en_24 := io.en(24)
  verilogBlackBox.io.ilro_en_25 := io.en(25)
  verilogBlackBox.io.ilro_en_26 := io.en(26)
  verilogBlackBox.io.ilro_en_27 := io.en(27)
  verilogBlackBox.io.ilro_en_28 := io.en(28)
  verilogBlackBox.io.ilro_en_29 := io.en(29)
  verilogBlackBox.io.ilro_en_30 := io.en(30)
  verilogBlackBox.io.ilro_en_31 := io.en(31)
  verilogBlackBox.io.ilro_en_32 := io.en(32)
  verilogBlackBox.io.ilro_en_33 := io.en(33)
  verilogBlackBox.io.ilro_en_34 := io.en(34)
  verilogBlackBox.io.ilro_en_35 := io.en(35)
  verilogBlackBox.io.ilro_en_36 := io.en(36)
  verilogBlackBox.io.ilro_en_37 := io.en(37)
  verilogBlackBox.io.ilro_en_38 := io.en(38)
  verilogBlackBox.io.ilro_en_39 := io.en(39)
  verilogBlackBox.io.ilro_en_40 := io.en(40)
  verilogBlackBox.io.ilro_en_41 := io.en(41)
  verilogBlackBox.io.ilro_en_42 := io.en(42)
  verilogBlackBox.io.ilro_en_43 := io.en(43)
  verilogBlackBox.io.ilro_en_44 := io.en(44)
  verilogBlackBox.io.ilro_en_45 := io.en(45)
  verilogBlackBox.io.ilro_en_46 := io.en(46)
  verilogBlackBox.io.ilro_en_47 := io.en(47)
  verilogBlackBox.io.ilro_en_48 := io.en(48)
  verilogBlackBox.io.ilro_en_49 := io.en(49)
  verilogBlackBox.io.ilro_en_50 := io.en(50)
  verilogBlackBox.io.ilro_en_51 := io.en(51)
  verilogBlackBox.io.ilro_en_52 := io.en(52)
  verilogBlackBox.io.ilro_en_53 := io.en(53)
  verilogBlackBox.io.ilro_en_54 := io.en(54)
  verilogBlackBox.io.ilro_en_55 := io.en(55)
  verilogBlackBox.io.ilro_en_56 := io.en(56)
  verilogBlackBox.io.ilro_en_57 := io.en(57)
  verilogBlackBox.io.ilro_en_58 := io.en(58)
  verilogBlackBox.io.ilro_en_59 := io.en(59)
  verilogBlackBox.io.ilro_en_60 := io.en(60)
  verilogBlackBox.io.ilro_en_61 := io.en(61)
  verilogBlackBox.io.ilro_en_62 := io.en(62)
  verilogBlackBox.io.ilro_en_63 := io.en(63)
  verilogBlackBox.io.ilro_enb_0 := io.en(0)
  verilogBlackBox.io.ilro_enb_1 := io.en(1)
  verilogBlackBox.io.ilro_enb_2 := io.en(2)
  verilogBlackBox.io.ilro_enb_3 := io.en(3)
  verilogBlackBox.io.ilro_enb_4 := io.en(4)
  verilogBlackBox.io.ilro_enb_5 := io.en(5)
  verilogBlackBox.io.ilro_enb_6 := io.en(6)
  verilogBlackBox.io.ilro_enb_7 := io.en(7)
  verilogBlackBox.io.ilro_enb_8 := io.en(8)
  verilogBlackBox.io.ilro_enb_9 := io.en(9)
  verilogBlackBox.io.ilro_enb_10 := io.en(10)
  verilogBlackBox.io.ilro_enb_11 := io.en(11)
  verilogBlackBox.io.ilro_enb_12 := io.en(12)
  verilogBlackBox.io.ilro_enb_13 := io.en(13)
  verilogBlackBox.io.ilro_enb_14 := io.en(14)
  verilogBlackBox.io.ilro_enb_15 := io.en(15)
  verilogBlackBox.io.ilro_enb_16 := io.en(16)
  verilogBlackBox.io.ilro_enb_17 := io.en(17)
  verilogBlackBox.io.ilro_enb_18 := io.en(18)
  verilogBlackBox.io.ilro_enb_19 := io.en(19)
  verilogBlackBox.io.ilro_enb_20 := io.en(20)
  verilogBlackBox.io.ilro_enb_21 := io.en(21)
  verilogBlackBox.io.ilro_enb_22 := io.en(22)
  verilogBlackBox.io.ilro_enb_23 := io.en(23)
  verilogBlackBox.io.ilro_enb_24 := io.en(24)
  verilogBlackBox.io.ilro_enb_25 := io.en(25)
  verilogBlackBox.io.ilro_enb_26 := io.en(26)
  verilogBlackBox.io.ilro_enb_27 := io.en(27)
  verilogBlackBox.io.ilro_enb_28 := io.en(28)
  verilogBlackBox.io.ilro_enb_29 := io.en(29)
  verilogBlackBox.io.ilro_enb_30 := io.en(30)
  verilogBlackBox.io.ilro_enb_31 := io.en(31)
  verilogBlackBox.io.ilro_enb_32 := io.en(32)
  verilogBlackBox.io.ilro_enb_33 := io.en(33)
  verilogBlackBox.io.ilro_enb_34 := io.en(34)
  verilogBlackBox.io.ilro_enb_35 := io.en(35)
  verilogBlackBox.io.ilro_enb_36 := io.en(36)
  verilogBlackBox.io.ilro_enb_37 := io.en(37)
  verilogBlackBox.io.ilro_enb_38 := io.en(38)
  verilogBlackBox.io.ilro_enb_39 := io.en(39)
  verilogBlackBox.io.ilro_enb_40 := io.en(40)
  verilogBlackBox.io.ilro_enb_41 := io.en(41)
  verilogBlackBox.io.ilro_enb_42 := io.en(42)
  verilogBlackBox.io.ilro_enb_43 := io.en(43)
  verilogBlackBox.io.ilro_enb_44 := io.en(44)
  verilogBlackBox.io.ilro_enb_45 := io.en(45)
  verilogBlackBox.io.ilro_enb_46 := io.en(46)
  verilogBlackBox.io.ilro_enb_47 := io.en(47)
  verilogBlackBox.io.ilro_enb_48 := io.en(48)
  verilogBlackBox.io.ilro_enb_49 := io.en(49)
  verilogBlackBox.io.ilro_enb_50 := io.en(50)
  verilogBlackBox.io.ilro_enb_51 := io.en(51)
  verilogBlackBox.io.ilro_enb_52 := io.en(52)
  verilogBlackBox.io.ilro_enb_53 := io.en(53)
  verilogBlackBox.io.ilro_enb_54 := io.en(54)
  verilogBlackBox.io.ilro_enb_55 := io.en(55)
  verilogBlackBox.io.ilro_enb_56 := io.en(56)
  verilogBlackBox.io.ilro_enb_57 := io.en(57)
  verilogBlackBox.io.ilro_enb_58 := io.en(58)
  verilogBlackBox.io.ilro_enb_59 := io.en(59)
  verilogBlackBox.io.ilro_enb_60 := io.en(60)
  verilogBlackBox.io.ilro_enb_61 := io.en(61)
  verilogBlackBox.io.ilro_enb_62 := io.en(62)
  verilogBlackBox.io.ilro_enb_63 := io.en(63)

  // io.txckp := io.injp
  // io.txckn := io.injm
  // 
  // io.driver0 <> 0.U.asTypeOf(io.driver0)
  // io.driver1 <> 0.U.asTypeOf(io.driver1)
  // io.driver0_en := true.B
  // io.driver1_en := true.B
  // io.driver0_en_b := false.B
  // io.driver1_en_b := false.B
}

class VerilogTxClkIO extends Bundle {
  val injp = Input(Bool())
  val injm = Input(Bool())
  val in = Input(Bool())
  val txckp = Output(Bool())
  val txckn = Output(Bool())
  val driver0_pu_ctl_0 = Input(Bool())
  val driver0_pu_ctl_1 = Input(Bool())
  val driver0_pu_ctl_2 = Input(Bool())
  val driver0_pu_ctl_3 = Input(Bool())
  val driver0_pu_ctl_4 = Input(Bool())
  val driver0_pu_ctl_5 = Input(Bool())
  val driver0_pu_ctl_6 = Input(Bool())
  val driver0_pu_ctl_7 = Input(Bool())
  val driver0_pu_ctl_8 = Input(Bool())
  val driver0_pu_ctl_9 = Input(Bool())
  val driver0_pu_ctl_10 = Input(Bool())
  val driver0_pu_ctl_11 = Input(Bool())
  val driver0_pu_ctl_12 = Input(Bool())
  val driver0_pu_ctl_13 = Input(Bool())
  val driver0_pu_ctl_14 = Input(Bool())
  val driver0_pu_ctl_15 = Input(Bool())
  val driver0_pu_ctl_16 = Input(Bool())
  val driver0_pu_ctl_17 = Input(Bool())
  val driver0_pu_ctl_18 = Input(Bool())
  val driver0_pu_ctl_19 = Input(Bool())
  val driver0_pu_ctl_20 = Input(Bool())
  val driver0_pu_ctl_21 = Input(Bool())
  val driver0_pu_ctl_22 = Input(Bool())
  val driver0_pu_ctl_23 = Input(Bool())
  val driver0_pu_ctl_24 = Input(Bool())
  val driver0_pu_ctl_25 = Input(Bool())
  val driver0_pu_ctl_26 = Input(Bool())
  val driver0_pu_ctl_27 = Input(Bool())
  val driver0_pu_ctl_28 = Input(Bool())
  val driver0_pu_ctl_29 = Input(Bool())
  val driver0_pu_ctl_30 = Input(Bool())
  val driver0_pu_ctl_31 = Input(Bool())
  val driver0_pu_ctl_32 = Input(Bool())
  val driver0_pu_ctl_33 = Input(Bool())
  val driver0_pu_ctl_34 = Input(Bool())
  val driver0_pu_ctl_35 = Input(Bool())
  val driver0_pu_ctl_36 = Input(Bool())
  val driver0_pu_ctl_37 = Input(Bool())
  val driver0_pu_ctl_38 = Input(Bool())
  val driver0_pu_ctl_39 = Input(Bool())
  val driver0_pu_ctl_40 = Input(Bool())
  val driver0_pu_ctl_41 = Input(Bool())
  val driver0_pu_ctl_42 = Input(Bool())
  val driver0_pu_ctl_43 = Input(Bool())
  val driver0_pu_ctl_44 = Input(Bool())
  val driver0_pu_ctl_45 = Input(Bool())
  val driver0_pu_ctl_46 = Input(Bool())
  val driver0_pu_ctl_47 = Input(Bool())
  val driver0_pd_ctlb_0 = Input(Bool())
  val driver0_pd_ctlb_1 = Input(Bool())
  val driver0_pd_ctlb_2 = Input(Bool())
  val driver0_pd_ctlb_3 = Input(Bool())
  val driver0_pd_ctlb_4 = Input(Bool())
  val driver0_pd_ctlb_5 = Input(Bool())
  val driver0_pd_ctlb_6 = Input(Bool())
  val driver0_pd_ctlb_7 = Input(Bool())
  val driver0_pd_ctlb_8 = Input(Bool())
  val driver0_pd_ctlb_9 = Input(Bool())
  val driver0_pd_ctlb_10 = Input(Bool())
  val driver0_pd_ctlb_11 = Input(Bool())
  val driver0_pd_ctlb_12 = Input(Bool())
  val driver0_pd_ctlb_13 = Input(Bool())
  val driver0_pd_ctlb_14 = Input(Bool())
  val driver0_pd_ctlb_15 = Input(Bool())
  val driver0_pd_ctlb_16 = Input(Bool())
  val driver0_pd_ctlb_17 = Input(Bool())
  val driver0_pd_ctlb_18 = Input(Bool())
  val driver0_pd_ctlb_19 = Input(Bool())
  val driver0_pd_ctlb_20 = Input(Bool())
  val driver0_pd_ctlb_21 = Input(Bool())
  val driver0_pd_ctlb_22 = Input(Bool())
  val driver0_pd_ctlb_23 = Input(Bool())
  val driver0_pd_ctlb_24 = Input(Bool())
  val driver0_pd_ctlb_25 = Input(Bool())
  val driver0_pd_ctlb_26 = Input(Bool())
  val driver0_pd_ctlb_27 = Input(Bool())
  val driver0_pd_ctlb_28 = Input(Bool())
  val driver0_pd_ctlb_29 = Input(Bool())
  val driver0_pd_ctlb_30 = Input(Bool())
  val driver0_pd_ctlb_31 = Input(Bool())
  val driver0_pd_ctlb_32 = Input(Bool())
  val driver0_pd_ctlb_33 = Input(Bool())
  val driver0_pd_ctlb_34 = Input(Bool())
  val driver0_pd_ctlb_35 = Input(Bool())
  val driver0_pd_ctlb_36 = Input(Bool())
  val driver0_pd_ctlb_37 = Input(Bool())
  val driver0_pd_ctlb_38 = Input(Bool())
  val driver0_pd_ctlb_39 = Input(Bool())
  val driver0_pd_ctlb_40 = Input(Bool())
  val driver0_pd_ctlb_41 = Input(Bool())
  val driver0_pd_ctlb_42 = Input(Bool())
  val driver0_pd_ctlb_43 = Input(Bool())
  val driver0_pd_ctlb_44 = Input(Bool())
  val driver0_pd_ctlb_45 = Input(Bool())
  val driver0_pd_ctlb_46 = Input(Bool())
  val driver0_pd_ctlb_47 = Input(Bool())
  val driver0_en = Input(Bool()) 
  val driver0_en_b = Input(Bool()) 
  val pu_ctl_p_0 = Input(Bool())
  val pu_ctl_p_1 = Input(Bool())
  val pu_ctl_p_2 = Input(Bool())
  val pu_ctl_p_3 = Input(Bool())
  val pu_ctl_p_4 = Input(Bool())
  val pu_ctl_p_5 = Input(Bool())
  val pu_ctl_p_6 = Input(Bool())
  val pu_ctl_p_7 = Input(Bool())
  val pu_ctl_p_8 = Input(Bool())
  val pu_ctl_p_9 = Input(Bool())
  val pu_ctl_p_10 = Input(Bool())
  val pu_ctl_p_11 = Input(Bool())
  val pu_ctl_p_12 = Input(Bool())
  val pu_ctl_p_13 = Input(Bool())
  val pu_ctl_p_14 = Input(Bool())
  val pu_ctl_p_15 = Input(Bool())
  val pu_ctl_p_16 = Input(Bool())
  val pu_ctl_p_17 = Input(Bool())
  val pu_ctl_p_18 = Input(Bool())
  val pu_ctl_p_19 = Input(Bool())
  val pu_ctl_p_20 = Input(Bool())
  val pu_ctl_p_21 = Input(Bool())
  val pu_ctl_p_22 = Input(Bool())
  val pu_ctl_p_23 = Input(Bool())
  val pu_ctl_p_24 = Input(Bool())
  val pu_ctl_p_25 = Input(Bool())
  val pu_ctl_p_26 = Input(Bool())
  val pu_ctl_p_27 = Input(Bool())
  val pu_ctl_p_28 = Input(Bool())
  val pu_ctl_p_29 = Input(Bool())
  val pu_ctl_p_30 = Input(Bool())
  val pu_ctl_p_31 = Input(Bool())
  val pu_ctl_p_32 = Input(Bool())
  val pu_ctl_p_33 = Input(Bool())
  val pu_ctl_p_34 = Input(Bool())
  val pu_ctl_p_35 = Input(Bool())
  val pu_ctl_p_36 = Input(Bool())
  val pu_ctl_p_37 = Input(Bool())
  val pu_ctl_p_38 = Input(Bool())
  val pu_ctl_p_39 = Input(Bool())
  val pu_ctl_p_40 = Input(Bool())
  val pu_ctl_p_41 = Input(Bool())
  val pu_ctl_p_42 = Input(Bool())
  val pu_ctl_p_43 = Input(Bool())
  val pu_ctl_p_44 = Input(Bool())
  val pu_ctl_p_45 = Input(Bool())
  val pu_ctl_p_46 = Input(Bool())
  val pu_ctl_p_47 = Input(Bool())
  val pd_ctlb_p_0 = Input(Bool())
  val pd_ctlb_p_1 = Input(Bool())
  val pd_ctlb_p_2 = Input(Bool())
  val pd_ctlb_p_3 = Input(Bool())
  val pd_ctlb_p_4 = Input(Bool())
  val pd_ctlb_p_5 = Input(Bool())
  val pd_ctlb_p_6 = Input(Bool())
  val pd_ctlb_p_7 = Input(Bool())
  val pd_ctlb_p_8 = Input(Bool())
  val pd_ctlb_p_9 = Input(Bool())
  val pd_ctlb_p_10 = Input(Bool())
  val pd_ctlb_p_11 = Input(Bool())
  val pd_ctlb_p_12 = Input(Bool())
  val pd_ctlb_p_13 = Input(Bool())
  val pd_ctlb_p_14 = Input(Bool())
  val pd_ctlb_p_15 = Input(Bool())
  val pd_ctlb_p_16 = Input(Bool())
  val pd_ctlb_p_17 = Input(Bool())
  val pd_ctlb_p_18 = Input(Bool())
  val pd_ctlb_p_19 = Input(Bool())
  val pd_ctlb_p_20 = Input(Bool())
  val pd_ctlb_p_21 = Input(Bool())
  val pd_ctlb_p_22 = Input(Bool())
  val pd_ctlb_p_23 = Input(Bool())
  val pd_ctlb_p_24 = Input(Bool())
  val pd_ctlb_p_25 = Input(Bool())
  val pd_ctlb_p_26 = Input(Bool())
  val pd_ctlb_p_27 = Input(Bool())
  val pd_ctlb_p_28 = Input(Bool())
  val pd_ctlb_p_29 = Input(Bool())
  val pd_ctlb_p_30 = Input(Bool())
  val pd_ctlb_p_31 = Input(Bool())
  val pd_ctlb_p_32 = Input(Bool())
  val pd_ctlb_p_33 = Input(Bool())
  val pd_ctlb_p_34 = Input(Bool())
  val pd_ctlb_p_35 = Input(Bool())
  val pd_ctlb_p_36 = Input(Bool())
  val pd_ctlb_p_37 = Input(Bool())
  val pd_ctlb_p_38 = Input(Bool())
  val pd_ctlb_p_39 = Input(Bool())
  val pd_ctlb_p_40 = Input(Bool())
  val pd_ctlb_p_41 = Input(Bool())
  val pd_ctlb_p_42 = Input(Bool())
  val pd_ctlb_p_43 = Input(Bool())
  val pd_ctlb_p_44 = Input(Bool())
  val pd_ctlb_p_45 = Input(Bool())
  val pd_ctlb_p_46 = Input(Bool())
  val pd_ctlb_p_47 = Input(Bool())
  val en_p = Input(Bool()) 
  val en_b_p = Input(Bool()) 
  val ilro_en_0 = Input(Bool())
  val ilro_en_1 = Input(Bool())
  val ilro_en_2 = Input(Bool())
  val ilro_en_3 = Input(Bool())
  val ilro_en_4 = Input(Bool())
  val ilro_en_5 = Input(Bool())
  val ilro_en_6 = Input(Bool())
  val ilro_en_7 = Input(Bool())
  val ilro_en_8 = Input(Bool())
  val ilro_en_9 = Input(Bool())
  val ilro_en_10 = Input(Bool())
  val ilro_en_11 = Input(Bool())
  val ilro_en_12 = Input(Bool())
  val ilro_en_13 = Input(Bool())
  val ilro_en_14 = Input(Bool())
  val ilro_en_15 = Input(Bool())
  val ilro_en_16 = Input(Bool())
  val ilro_en_17 = Input(Bool())
  val ilro_en_18 = Input(Bool())
  val ilro_en_19 = Input(Bool())
  val ilro_en_20 = Input(Bool())
  val ilro_en_21 = Input(Bool())
  val ilro_en_22 = Input(Bool())
  val ilro_en_23 = Input(Bool())
  val ilro_en_24 = Input(Bool())
  val ilro_en_25 = Input(Bool())
  val ilro_en_26 = Input(Bool())
  val ilro_en_27 = Input(Bool())
  val ilro_en_28 = Input(Bool())
  val ilro_en_29 = Input(Bool())
  val ilro_en_30 = Input(Bool())
  val ilro_en_31 = Input(Bool())
  val ilro_en_32 = Input(Bool())
  val ilro_en_33 = Input(Bool())
  val ilro_en_34 = Input(Bool())
  val ilro_en_35 = Input(Bool())
  val ilro_en_36 = Input(Bool())
  val ilro_en_37 = Input(Bool())
  val ilro_en_38 = Input(Bool())
  val ilro_en_39 = Input(Bool())
  val ilro_en_40 = Input(Bool())
  val ilro_en_41 = Input(Bool())
  val ilro_en_42 = Input(Bool())
  val ilro_en_43 = Input(Bool())
  val ilro_en_44 = Input(Bool())
  val ilro_en_45 = Input(Bool())
  val ilro_en_46 = Input(Bool())
  val ilro_en_47 = Input(Bool())
  val ilro_en_48 = Input(Bool())
  val ilro_en_49 = Input(Bool())
  val ilro_en_50 = Input(Bool())
  val ilro_en_51 = Input(Bool())
  val ilro_en_52 = Input(Bool())
  val ilro_en_53 = Input(Bool())
  val ilro_en_54 = Input(Bool())
  val ilro_en_55 = Input(Bool())
  val ilro_en_56 = Input(Bool())
  val ilro_en_57 = Input(Bool())
  val ilro_en_58 = Input(Bool())
  val ilro_en_59 = Input(Bool())
  val ilro_en_60 = Input(Bool())
  val ilro_en_61 = Input(Bool())
  val ilro_en_62 = Input(Bool())
  val ilro_en_63 = Input(Bool())
  val ilro_en_64 = Input(Bool())
  val ilro_enb_0 = Input(Bool())
  val ilro_enb_1 = Input(Bool())
  val ilro_enb_2 = Input(Bool())
  val ilro_enb_3 = Input(Bool())
  val ilro_enb_4 = Input(Bool())
  val ilro_enb_5 = Input(Bool())
  val ilro_enb_6 = Input(Bool())
  val ilro_enb_7 = Input(Bool())
  val ilro_enb_8 = Input(Bool())
  val ilro_enb_9 = Input(Bool())
  val ilro_enb_10 = Input(Bool())
  val ilro_enb_11 = Input(Bool())
  val ilro_enb_12 = Input(Bool())
  val ilro_enb_13 = Input(Bool())
  val ilro_enb_14 = Input(Bool())
  val ilro_enb_15 = Input(Bool())
  val ilro_enb_16 = Input(Bool())
  val ilro_enb_17 = Input(Bool())
  val ilro_enb_18 = Input(Bool())
  val ilro_enb_19 = Input(Bool())
  val ilro_enb_20 = Input(Bool())
  val ilro_enb_21 = Input(Bool())
  val ilro_enb_22 = Input(Bool())
  val ilro_enb_23 = Input(Bool())
  val ilro_enb_24 = Input(Bool())
  val ilro_enb_25 = Input(Bool())
  val ilro_enb_26 = Input(Bool())
  val ilro_enb_27 = Input(Bool())
  val ilro_enb_28 = Input(Bool())
  val ilro_enb_29 = Input(Bool())
  val ilro_enb_30 = Input(Bool())
  val ilro_enb_31 = Input(Bool())
  val ilro_enb_32 = Input(Bool())
  val ilro_enb_33 = Input(Bool())
  val ilro_enb_34 = Input(Bool())
  val ilro_enb_35 = Input(Bool())
  val ilro_enb_36 = Input(Bool())
  val ilro_enb_37 = Input(Bool())
  val ilro_enb_38 = Input(Bool())
  val ilro_enb_39 = Input(Bool())
  val ilro_enb_40 = Input(Bool())
  val ilro_enb_41 = Input(Bool())
  val ilro_enb_42 = Input(Bool())
  val ilro_enb_43 = Input(Bool())
  val ilro_enb_44 = Input(Bool())
  val ilro_enb_45 = Input(Bool())
  val ilro_enb_46 = Input(Bool())
  val ilro_enb_47 = Input(Bool())
  val ilro_enb_48 = Input(Bool())
  val ilro_enb_49 = Input(Bool())
  val ilro_enb_50 = Input(Bool())
  val ilro_enb_51 = Input(Bool())
  val ilro_enb_52 = Input(Bool())
  val ilro_enb_53 = Input(Bool())
  val ilro_enb_54 = Input(Bool())
  val ilro_enb_55 = Input(Bool())
  val ilro_enb_56 = Input(Bool())
  val ilro_enb_57 = Input(Bool())
  val ilro_enb_58 = Input(Bool())
  val ilro_enb_59 = Input(Bool())
  val ilro_enb_60 = Input(Bool())
  val ilro_enb_61 = Input(Bool())
  val ilro_enb_62 = Input(Bool())
  val ilro_enb_63 = Input(Bool())
  val ilro_enb_64 = Input(Bool())
}

class VerilogTxClk extends BlackBox {
  val io = IO(new VerilogTxClkIO)

  override val desiredName = "TX_clk_tile"
}

class TxDriverIO extends Bundle {
  val din = Input(Bool())
  val dout = Output(Bool())
  val driver_ctl = new DriverControlIO
}

class TxDriver extends RawModule {
  val io = IO(new TxDriverIO)

  val verilogBlackBox = Module(new VerilogTxDriver)
  verilogBlackBox.io.clkin := io.din
  io.dout := verilogBlackBox.io.clkout
  verilogBlackBox.io.pu_ctl_0  := io.driver_ctl.pu_ctl.pu_ctl_0
  verilogBlackBox.io.pu_ctl_1  := io.driver_ctl.pu_ctl.pu_ctl_1
  verilogBlackBox.io.pu_ctl_2  := io.driver_ctl.pu_ctl.pu_ctl_2
  verilogBlackBox.io.pu_ctl_3  := io.driver_ctl.pu_ctl.pu_ctl_3
  verilogBlackBox.io.pu_ctl_4  := io.driver_ctl.pu_ctl.pu_ctl_4
  verilogBlackBox.io.pu_ctl_5  := io.driver_ctl.pu_ctl.pu_ctl_5
  verilogBlackBox.io.pu_ctl_6  := io.driver_ctl.pu_ctl.pu_ctl_6
  verilogBlackBox.io.pu_ctl_7  := io.driver_ctl.pu_ctl.pu_ctl_7
  verilogBlackBox.io.pu_ctl_8  := io.driver_ctl.pu_ctl.pu_ctl_8
  verilogBlackBox.io.pu_ctl_9  := io.driver_ctl.pu_ctl.pu_ctl_9
  verilogBlackBox.io.pu_ctl_10 := io.driver_ctl.pu_ctl.pu_ctl_10
  verilogBlackBox.io.pu_ctl_11 := io.driver_ctl.pu_ctl.pu_ctl_11
  verilogBlackBox.io.pu_ctl_12 := io.driver_ctl.pu_ctl.pu_ctl_12
  verilogBlackBox.io.pu_ctl_13 := io.driver_ctl.pu_ctl.pu_ctl_13
  verilogBlackBox.io.pu_ctl_14 := io.driver_ctl.pu_ctl.pu_ctl_14
  verilogBlackBox.io.pu_ctl_15 := io.driver_ctl.pu_ctl.pu_ctl_15
  verilogBlackBox.io.pu_ctl_16 := io.driver_ctl.pu_ctl.pu_ctl_16
  verilogBlackBox.io.pu_ctl_17 := io.driver_ctl.pu_ctl.pu_ctl_17
  verilogBlackBox.io.pu_ctl_18 := io.driver_ctl.pu_ctl.pu_ctl_18
  verilogBlackBox.io.pu_ctl_19 := io.driver_ctl.pu_ctl.pu_ctl_19
  verilogBlackBox.io.pu_ctl_20 := io.driver_ctl.pu_ctl.pu_ctl_20
  verilogBlackBox.io.pu_ctl_21 := io.driver_ctl.pu_ctl.pu_ctl_21
  verilogBlackBox.io.pu_ctl_22 := io.driver_ctl.pu_ctl.pu_ctl_22
  verilogBlackBox.io.pu_ctl_23 := io.driver_ctl.pu_ctl.pu_ctl_23
  verilogBlackBox.io.pu_ctl_24 := io.driver_ctl.pu_ctl.pu_ctl_24
  verilogBlackBox.io.pu_ctl_25 := io.driver_ctl.pu_ctl.pu_ctl_25
  verilogBlackBox.io.pu_ctl_26 := io.driver_ctl.pu_ctl.pu_ctl_26
  verilogBlackBox.io.pu_ctl_27 := io.driver_ctl.pu_ctl.pu_ctl_27
  verilogBlackBox.io.pu_ctl_28 := io.driver_ctl.pu_ctl.pu_ctl_28
  verilogBlackBox.io.pu_ctl_29 := io.driver_ctl.pu_ctl.pu_ctl_29
  verilogBlackBox.io.pu_ctl_30 := io.driver_ctl.pu_ctl.pu_ctl_30
  verilogBlackBox.io.pu_ctl_31 := io.driver_ctl.pu_ctl.pu_ctl_31
  verilogBlackBox.io.pu_ctl_32 := io.driver_ctl.pu_ctl.pu_ctl_32
  verilogBlackBox.io.pu_ctl_33 := io.driver_ctl.pu_ctl.pu_ctl_33
  verilogBlackBox.io.pu_ctl_34 := io.driver_ctl.pu_ctl.pu_ctl_34
  verilogBlackBox.io.pu_ctl_35 := io.driver_ctl.pu_ctl.pu_ctl_35
  verilogBlackBox.io.pu_ctl_36 := io.driver_ctl.pu_ctl.pu_ctl_36
  verilogBlackBox.io.pu_ctl_37 := io.driver_ctl.pu_ctl.pu_ctl_37
  verilogBlackBox.io.pu_ctl_38 := io.driver_ctl.pu_ctl.pu_ctl_38
  verilogBlackBox.io.pu_ctl_39 := io.driver_ctl.pu_ctl.pu_ctl_39
  verilogBlackBox.io.pu_ctl_40 := io.driver_ctl.pu_ctl.pu_ctl_40
  verilogBlackBox.io.pu_ctl_41 := io.driver_ctl.pu_ctl.pu_ctl_41
  verilogBlackBox.io.pu_ctl_42 := io.driver_ctl.pu_ctl.pu_ctl_42
  verilogBlackBox.io.pu_ctl_43 := io.driver_ctl.pu_ctl.pu_ctl_43
  verilogBlackBox.io.pu_ctl_44 := io.driver_ctl.pu_ctl.pu_ctl_44
  verilogBlackBox.io.pu_ctl_45 := io.driver_ctl.pu_ctl.pu_ctl_45
  verilogBlackBox.io.pu_ctl_46 := io.driver_ctl.pu_ctl.pu_ctl_46
  verilogBlackBox.io.pu_ctl_47 := io.driver_ctl.pu_ctl.pu_ctl_47
  verilogBlackBox.io.pd_ctlb_0  := io.driver_ctl.pd_ctlb.pd_ctlb_0
  verilogBlackBox.io.pd_ctlb_1  := io.driver_ctl.pd_ctlb.pd_ctlb_1
  verilogBlackBox.io.pd_ctlb_2  := io.driver_ctl.pd_ctlb.pd_ctlb_2
  verilogBlackBox.io.pd_ctlb_3  := io.driver_ctl.pd_ctlb.pd_ctlb_3
  verilogBlackBox.io.pd_ctlb_4  := io.driver_ctl.pd_ctlb.pd_ctlb_4
  verilogBlackBox.io.pd_ctlb_5  := io.driver_ctl.pd_ctlb.pd_ctlb_5
  verilogBlackBox.io.pd_ctlb_6  := io.driver_ctl.pd_ctlb.pd_ctlb_6
  verilogBlackBox.io.pd_ctlb_7  := io.driver_ctl.pd_ctlb.pd_ctlb_7
  verilogBlackBox.io.pd_ctlb_8  := io.driver_ctl.pd_ctlb.pd_ctlb_8
  verilogBlackBox.io.pd_ctlb_9  := io.driver_ctl.pd_ctlb.pd_ctlb_9
  verilogBlackBox.io.pd_ctlb_10 := io.driver_ctl.pd_ctlb.pd_ctlb_10
  verilogBlackBox.io.pd_ctlb_11 := io.driver_ctl.pd_ctlb.pd_ctlb_11
  verilogBlackBox.io.pd_ctlb_12 := io.driver_ctl.pd_ctlb.pd_ctlb_12
  verilogBlackBox.io.pd_ctlb_13 := io.driver_ctl.pd_ctlb.pd_ctlb_13
  verilogBlackBox.io.pd_ctlb_14 := io.driver_ctl.pd_ctlb.pd_ctlb_14
  verilogBlackBox.io.pd_ctlb_15 := io.driver_ctl.pd_ctlb.pd_ctlb_15
  verilogBlackBox.io.pd_ctlb_16 := io.driver_ctl.pd_ctlb.pd_ctlb_16
  verilogBlackBox.io.pd_ctlb_17 := io.driver_ctl.pd_ctlb.pd_ctlb_17
  verilogBlackBox.io.pd_ctlb_18 := io.driver_ctl.pd_ctlb.pd_ctlb_18
  verilogBlackBox.io.pd_ctlb_19 := io.driver_ctl.pd_ctlb.pd_ctlb_19
  verilogBlackBox.io.pd_ctlb_20 := io.driver_ctl.pd_ctlb.pd_ctlb_20
  verilogBlackBox.io.pd_ctlb_21 := io.driver_ctl.pd_ctlb.pd_ctlb_21
  verilogBlackBox.io.pd_ctlb_22 := io.driver_ctl.pd_ctlb.pd_ctlb_22
  verilogBlackBox.io.pd_ctlb_23 := io.driver_ctl.pd_ctlb.pd_ctlb_23
  verilogBlackBox.io.pd_ctlb_24 := io.driver_ctl.pd_ctlb.pd_ctlb_24
  verilogBlackBox.io.pd_ctlb_25 := io.driver_ctl.pd_ctlb.pd_ctlb_25
  verilogBlackBox.io.pd_ctlb_26 := io.driver_ctl.pd_ctlb.pd_ctlb_26
  verilogBlackBox.io.pd_ctlb_27 := io.driver_ctl.pd_ctlb.pd_ctlb_27
  verilogBlackBox.io.pd_ctlb_28 := io.driver_ctl.pd_ctlb.pd_ctlb_28
  verilogBlackBox.io.pd_ctlb_29 := io.driver_ctl.pd_ctlb.pd_ctlb_29
  verilogBlackBox.io.pd_ctlb_30 := io.driver_ctl.pd_ctlb.pd_ctlb_30
  verilogBlackBox.io.pd_ctlb_31 := io.driver_ctl.pd_ctlb.pd_ctlb_31
  verilogBlackBox.io.pd_ctlb_32 := io.driver_ctl.pd_ctlb.pd_ctlb_32
  verilogBlackBox.io.pd_ctlb_33 := io.driver_ctl.pd_ctlb.pd_ctlb_33
  verilogBlackBox.io.pd_ctlb_34 := io.driver_ctl.pd_ctlb.pd_ctlb_34
  verilogBlackBox.io.pd_ctlb_35 := io.driver_ctl.pd_ctlb.pd_ctlb_35
  verilogBlackBox.io.pd_ctlb_36 := io.driver_ctl.pd_ctlb.pd_ctlb_36
  verilogBlackBox.io.pd_ctlb_37 := io.driver_ctl.pd_ctlb.pd_ctlb_37
  verilogBlackBox.io.pd_ctlb_38 := io.driver_ctl.pd_ctlb.pd_ctlb_38
  verilogBlackBox.io.pd_ctlb_39 := io.driver_ctl.pd_ctlb.pd_ctlb_39
  verilogBlackBox.io.pd_ctlb_40 := io.driver_ctl.pd_ctlb.pd_ctlb_40
  verilogBlackBox.io.pd_ctlb_41 := io.driver_ctl.pd_ctlb.pd_ctlb_41
  verilogBlackBox.io.pd_ctlb_42 := io.driver_ctl.pd_ctlb.pd_ctlb_42
  verilogBlackBox.io.pd_ctlb_43 := io.driver_ctl.pd_ctlb.pd_ctlb_43
  verilogBlackBox.io.pd_ctlb_44 := io.driver_ctl.pd_ctlb.pd_ctlb_44
  verilogBlackBox.io.pd_ctlb_45 := io.driver_ctl.pd_ctlb.pd_ctlb_45
  verilogBlackBox.io.pd_ctlb_46 := io.driver_ctl.pd_ctlb.pd_ctlb_46
  verilogBlackBox.io.pd_ctlb_47 := io.driver_ctl.pd_ctlb.pd_ctlb_47
  verilogBlackBox.io.en := io.driver_ctl.en
  verilogBlackBox.io.en_b := io.driver_ctl.en_b

  // io.dout := io.din
}
class VerilogTxDriverIO extends Bundle {
  val clkin = Input(Bool())
  val clkout = Output(Bool())
  val pu_ctl_0 = Input(Bool())
  val pu_ctl_1 = Input(Bool())
  val pu_ctl_2 = Input(Bool())
  val pu_ctl_3 = Input(Bool())
  val pu_ctl_4 = Input(Bool())
  val pu_ctl_5 = Input(Bool())
  val pu_ctl_6 = Input(Bool())
  val pu_ctl_7 = Input(Bool())
  val pu_ctl_8 = Input(Bool())
  val pu_ctl_9 = Input(Bool())
  val pu_ctl_10 = Input(Bool())
  val pu_ctl_11 = Input(Bool())
  val pu_ctl_12 = Input(Bool())
  val pu_ctl_13 = Input(Bool())
  val pu_ctl_14 = Input(Bool())
  val pu_ctl_15 = Input(Bool())
  val pu_ctl_16 = Input(Bool())
  val pu_ctl_17 = Input(Bool())
  val pu_ctl_18 = Input(Bool())
  val pu_ctl_19 = Input(Bool())
  val pu_ctl_20 = Input(Bool())
  val pu_ctl_21 = Input(Bool())
  val pu_ctl_22 = Input(Bool())
  val pu_ctl_23 = Input(Bool())
  val pu_ctl_24 = Input(Bool())
  val pu_ctl_25 = Input(Bool())
  val pu_ctl_26 = Input(Bool())
  val pu_ctl_27 = Input(Bool())
  val pu_ctl_28 = Input(Bool())
  val pu_ctl_29 = Input(Bool())
  val pu_ctl_30 = Input(Bool())
  val pu_ctl_31 = Input(Bool())
  val pu_ctl_32 = Input(Bool())
  val pu_ctl_33 = Input(Bool())
  val pu_ctl_34 = Input(Bool())
  val pu_ctl_35 = Input(Bool())
  val pu_ctl_36 = Input(Bool())
  val pu_ctl_37 = Input(Bool())
  val pu_ctl_38 = Input(Bool())
  val pu_ctl_39 = Input(Bool())
  val pu_ctl_40 = Input(Bool())
  val pu_ctl_41 = Input(Bool())
  val pu_ctl_42 = Input(Bool())
  val pu_ctl_43 = Input(Bool())
  val pu_ctl_44 = Input(Bool())
  val pu_ctl_45 = Input(Bool())
  val pu_ctl_46 = Input(Bool())
  val pu_ctl_47 = Input(Bool())
  val pd_ctlb_0 = Input(Bool())
  val pd_ctlb_1 = Input(Bool())
  val pd_ctlb_2 = Input(Bool())
  val pd_ctlb_3 = Input(Bool())
  val pd_ctlb_4 = Input(Bool())
  val pd_ctlb_5 = Input(Bool())
  val pd_ctlb_6 = Input(Bool())
  val pd_ctlb_7 = Input(Bool())
  val pd_ctlb_8 = Input(Bool())
  val pd_ctlb_9 = Input(Bool())
  val pd_ctlb_10 = Input(Bool())
  val pd_ctlb_11 = Input(Bool())
  val pd_ctlb_12 = Input(Bool())
  val pd_ctlb_13 = Input(Bool())
  val pd_ctlb_14 = Input(Bool())
  val pd_ctlb_15 = Input(Bool())
  val pd_ctlb_16 = Input(Bool())
  val pd_ctlb_17 = Input(Bool())
  val pd_ctlb_18 = Input(Bool())
  val pd_ctlb_19 = Input(Bool())
  val pd_ctlb_20 = Input(Bool())
  val pd_ctlb_21 = Input(Bool())
  val pd_ctlb_22 = Input(Bool())
  val pd_ctlb_23 = Input(Bool())
  val pd_ctlb_24 = Input(Bool())
  val pd_ctlb_25 = Input(Bool())
  val pd_ctlb_26 = Input(Bool())
  val pd_ctlb_27 = Input(Bool())
  val pd_ctlb_28 = Input(Bool())
  val pd_ctlb_29 = Input(Bool())
  val pd_ctlb_30 = Input(Bool())
  val pd_ctlb_31 = Input(Bool())
  val pd_ctlb_32 = Input(Bool())
  val pd_ctlb_33 = Input(Bool())
  val pd_ctlb_34 = Input(Bool())
  val pd_ctlb_35 = Input(Bool())
  val pd_ctlb_36 = Input(Bool())
  val pd_ctlb_37 = Input(Bool())
  val pd_ctlb_38 = Input(Bool())
  val pd_ctlb_39 = Input(Bool())
  val pd_ctlb_40 = Input(Bool())
  val pd_ctlb_41 = Input(Bool())
  val pd_ctlb_42 = Input(Bool())
  val pd_ctlb_43 = Input(Bool())
  val pd_ctlb_44 = Input(Bool())
  val pd_ctlb_45 = Input(Bool())
  val pd_ctlb_46 = Input(Bool())
  val pd_ctlb_47 = Input(Bool())
  val en = Input(Bool()) 
  val en_b = Input(Bool()) 
}

class VerilogTxDriver extends BlackBox {
  val io = IO(new VerilogTxDriverIO)

  override val desiredName = "txclk"
}
