package uciephytest.phy

import chisel3._
import chisel3.util._

class DriverControlIO extends Bundle {
  val pu_ctl = new DriverPuControlIO
  val pd_ctlb = new DriverPdControlIO
  val en = Input(Bool()) 
  val en_b = Input(Bool()) 
}

class ClkDriverControlIO extends Bundle {
  val pu_ctl = new DriverPuControlIO
  val pd_ctlb = new DriverPdControlIO
}

class ClockingControlIO extends Bundle {
  // Use outputs for signals that do not need to be connected
  val VCM = Output(Bool())
  val in_buf = Output(Bits(8.W))
  val inbm = Output(Bool())
  val inbp = Output(Bool())
  val injmb = Output(Bool())
  val injpb = Output(Bool())
  val mid = Output(Bits(8.W))
  val mixer_out = Output(Bool())
  val mixer_outb = Output(Bool())
  val misc = new MiscClockingControlIO
  val en = Input(Bits(64.W))
  val enb = Input(Bits(64.W))
}

class TxLaneIO extends Bundle {
  val injp = Input(Bool())
  val injm = Input(Bool())
  val in = Input(Bool())
  val din = new TxDinIO
  val dout = Output(Bool())
  val divclk = Output(Clock())
  val resetb = Input(Bool())
  val driver_ctl = new DriverControlIO
  val clocking_ctl = new ClockingControlIO
}

class TxLane extends RawModule {
  val io = IO(new TxLaneIO)

  val verilogBlackBox = Module(new VerilogTxLane)
  verilogBlackBox.io.injp := io.injp
  verilogBlackBox.io.injm := io.injm
  verilogBlackBox.io.in := io.in
  verilogBlackBox.io.resetb := io.resetb
  verilogBlackBox.io.din_0 :=  io.din.din_0
  verilogBlackBox.io.din_1 :=  io.din.din_1
  verilogBlackBox.io.din_2 :=  io.din.din_2
  verilogBlackBox.io.din_3 :=  io.din.din_3
  verilogBlackBox.io.din_4 :=  io.din.din_4
  verilogBlackBox.io.din_5 :=  io.din.din_5
  verilogBlackBox.io.din_6 :=  io.din.din_6
  verilogBlackBox.io.din_7 :=  io.din.din_7
  verilogBlackBox.io.din_8 :=  io.din.din_8
  verilogBlackBox.io.din_9 :=  io.din.din_9
  verilogBlackBox.io.din_10 := io.din.din_10
  verilogBlackBox.io.din_11 := io.din.din_11
  verilogBlackBox.io.din_12 := io.din.din_12
  verilogBlackBox.io.din_13 := io.din.din_13
  verilogBlackBox.io.din_14 := io.din.din_14
  verilogBlackBox.io.din_15 := io.din.din_15
  io.dout := verilogBlackBox.io.dout
  io.divclk := verilogBlackBox.io.divclk
  verilogBlackBox.io.pu_ctl_0  := io.driver_ctl.pu_ctl.pu_ctl_0
  verilogBlackBox.io.pu_ctl_1  := io.driver_ctl.pu_ctl.pu_ctl_1
  verilogBlackBox.io.pu_ctl_2  := io.driver_ctl.pu_ctl.pu_ctl_2
  verilogBlackBox.io.pu_ctl_3  := io.driver_ctl.pu_ctl.pu_ctl_3
  verilogBlackBox.io.pu_ctl_4  := io.driver_ctl.pu_ctl.pu_ctl_4
  verilogBlackBox.io.pu_ctl_5  := io.driver_ctl.pu_ctl.pu_ctl_5
  verilogBlackBox.io.pu_ctl_6  := io.driver_ctl.pu_ctl.pu_ctl_6
  verilogBlackBox.io.pu_ctl_7  := io.driver_ctl.pu_ctl.pu_ctl_7
  verilogBlackBox.io.pu_ctl_8  := io.driver_ctl.pu_ctl.pu_ctl_8
  verilogBlackBox.io.pu_ctl_9  := io.driver_ctl.pu_ctl.pu_ctl_9
  verilogBlackBox.io.pu_ctl_10 := io.driver_ctl.pu_ctl.pu_ctl_10
  verilogBlackBox.io.pu_ctl_11 := io.driver_ctl.pu_ctl.pu_ctl_11
  verilogBlackBox.io.pu_ctl_12 := io.driver_ctl.pu_ctl.pu_ctl_12
  verilogBlackBox.io.pu_ctl_13 := io.driver_ctl.pu_ctl.pu_ctl_13
  verilogBlackBox.io.pu_ctl_14 := io.driver_ctl.pu_ctl.pu_ctl_14
  verilogBlackBox.io.pu_ctl_15 := io.driver_ctl.pu_ctl.pu_ctl_15
  verilogBlackBox.io.pu_ctl_16 := io.driver_ctl.pu_ctl.pu_ctl_16
  verilogBlackBox.io.pu_ctl_17 := io.driver_ctl.pu_ctl.pu_ctl_17
  verilogBlackBox.io.pu_ctl_18 := io.driver_ctl.pu_ctl.pu_ctl_18
  verilogBlackBox.io.pu_ctl_19 := io.driver_ctl.pu_ctl.pu_ctl_19
  verilogBlackBox.io.pu_ctl_20 := io.driver_ctl.pu_ctl.pu_ctl_20
  verilogBlackBox.io.pu_ctl_21 := io.driver_ctl.pu_ctl.pu_ctl_21
  verilogBlackBox.io.pu_ctl_22 := io.driver_ctl.pu_ctl.pu_ctl_22
  verilogBlackBox.io.pu_ctl_23 := io.driver_ctl.pu_ctl.pu_ctl_23
  verilogBlackBox.io.pu_ctl_24 := io.driver_ctl.pu_ctl.pu_ctl_24
  verilogBlackBox.io.pu_ctl_25 := io.driver_ctl.pu_ctl.pu_ctl_25
  verilogBlackBox.io.pu_ctl_26 := io.driver_ctl.pu_ctl.pu_ctl_26
  verilogBlackBox.io.pu_ctl_27 := io.driver_ctl.pu_ctl.pu_ctl_27
  verilogBlackBox.io.pu_ctl_28 := io.driver_ctl.pu_ctl.pu_ctl_28
  verilogBlackBox.io.pu_ctl_29 := io.driver_ctl.pu_ctl.pu_ctl_29
  verilogBlackBox.io.pu_ctl_30 := io.driver_ctl.pu_ctl.pu_ctl_30
  verilogBlackBox.io.pu_ctl_31 := io.driver_ctl.pu_ctl.pu_ctl_31
  verilogBlackBox.io.pu_ctl_32 := io.driver_ctl.pu_ctl.pu_ctl_32
  verilogBlackBox.io.pu_ctl_33 := io.driver_ctl.pu_ctl.pu_ctl_33
  verilogBlackBox.io.pu_ctl_34 := io.driver_ctl.pu_ctl.pu_ctl_34
  verilogBlackBox.io.pu_ctl_35 := io.driver_ctl.pu_ctl.pu_ctl_35
  verilogBlackBox.io.pu_ctl_36 := io.driver_ctl.pu_ctl.pu_ctl_36
  verilogBlackBox.io.pu_ctl_37 := io.driver_ctl.pu_ctl.pu_ctl_37
  verilogBlackBox.io.pu_ctl_38 := io.driver_ctl.pu_ctl.pu_ctl_38
  verilogBlackBox.io.pu_ctl_39 := io.driver_ctl.pu_ctl.pu_ctl_39
  verilogBlackBox.io.pu_ctl_40 := io.driver_ctl.pu_ctl.pu_ctl_40
  verilogBlackBox.io.pu_ctl_41 := io.driver_ctl.pu_ctl.pu_ctl_41
  verilogBlackBox.io.pu_ctl_42 := io.driver_ctl.pu_ctl.pu_ctl_42
  verilogBlackBox.io.pu_ctl_43 := io.driver_ctl.pu_ctl.pu_ctl_43
  verilogBlackBox.io.pu_ctl_44 := io.driver_ctl.pu_ctl.pu_ctl_44
  verilogBlackBox.io.pu_ctl_45 := io.driver_ctl.pu_ctl.pu_ctl_45
  verilogBlackBox.io.pu_ctl_46 := io.driver_ctl.pu_ctl.pu_ctl_46
  verilogBlackBox.io.pu_ctl_47 := io.driver_ctl.pu_ctl.pu_ctl_47
  verilogBlackBox.io.pd_ctlb_0  := io.driver_ctl.pd_ctlb.pd_ctlb_0
  verilogBlackBox.io.pd_ctlb_1  := io.driver_ctl.pd_ctlb.pd_ctlb_1
  verilogBlackBox.io.pd_ctlb_2  := io.driver_ctl.pd_ctlb.pd_ctlb_2
  verilogBlackBox.io.pd_ctlb_3  := io.driver_ctl.pd_ctlb.pd_ctlb_3
  verilogBlackBox.io.pd_ctlb_4  := io.driver_ctl.pd_ctlb.pd_ctlb_4
  verilogBlackBox.io.pd_ctlb_5  := io.driver_ctl.pd_ctlb.pd_ctlb_5
  verilogBlackBox.io.pd_ctlb_6  := io.driver_ctl.pd_ctlb.pd_ctlb_6
  verilogBlackBox.io.pd_ctlb_7  := io.driver_ctl.pd_ctlb.pd_ctlb_7
  verilogBlackBox.io.pd_ctlb_8  := io.driver_ctl.pd_ctlb.pd_ctlb_8
  verilogBlackBox.io.pd_ctlb_9  := io.driver_ctl.pd_ctlb.pd_ctlb_9
  verilogBlackBox.io.pd_ctlb_10 := io.driver_ctl.pd_ctlb.pd_ctlb_10
  verilogBlackBox.io.pd_ctlb_11 := io.driver_ctl.pd_ctlb.pd_ctlb_11
  verilogBlackBox.io.pd_ctlb_12 := io.driver_ctl.pd_ctlb.pd_ctlb_12
  verilogBlackBox.io.pd_ctlb_13 := io.driver_ctl.pd_ctlb.pd_ctlb_13
  verilogBlackBox.io.pd_ctlb_14 := io.driver_ctl.pd_ctlb.pd_ctlb_14
  verilogBlackBox.io.pd_ctlb_15 := io.driver_ctl.pd_ctlb.pd_ctlb_15
  verilogBlackBox.io.pd_ctlb_16 := io.driver_ctl.pd_ctlb.pd_ctlb_16
  verilogBlackBox.io.pd_ctlb_17 := io.driver_ctl.pd_ctlb.pd_ctlb_17
  verilogBlackBox.io.pd_ctlb_18 := io.driver_ctl.pd_ctlb.pd_ctlb_18
  verilogBlackBox.io.pd_ctlb_19 := io.driver_ctl.pd_ctlb.pd_ctlb_19
  verilogBlackBox.io.pd_ctlb_20 := io.driver_ctl.pd_ctlb.pd_ctlb_20
  verilogBlackBox.io.pd_ctlb_21 := io.driver_ctl.pd_ctlb.pd_ctlb_21
  verilogBlackBox.io.pd_ctlb_22 := io.driver_ctl.pd_ctlb.pd_ctlb_22
  verilogBlackBox.io.pd_ctlb_23 := io.driver_ctl.pd_ctlb.pd_ctlb_23
  verilogBlackBox.io.pd_ctlb_24 := io.driver_ctl.pd_ctlb.pd_ctlb_24
  verilogBlackBox.io.pd_ctlb_25 := io.driver_ctl.pd_ctlb.pd_ctlb_25
  verilogBlackBox.io.pd_ctlb_26 := io.driver_ctl.pd_ctlb.pd_ctlb_26
  verilogBlackBox.io.pd_ctlb_27 := io.driver_ctl.pd_ctlb.pd_ctlb_27
  verilogBlackBox.io.pd_ctlb_28 := io.driver_ctl.pd_ctlb.pd_ctlb_28
  verilogBlackBox.io.pd_ctlb_29 := io.driver_ctl.pd_ctlb.pd_ctlb_29
  verilogBlackBox.io.pd_ctlb_30 := io.driver_ctl.pd_ctlb.pd_ctlb_30
  verilogBlackBox.io.pd_ctlb_31 := io.driver_ctl.pd_ctlb.pd_ctlb_31
  verilogBlackBox.io.pd_ctlb_32 := io.driver_ctl.pd_ctlb.pd_ctlb_32
  verilogBlackBox.io.pd_ctlb_33 := io.driver_ctl.pd_ctlb.pd_ctlb_33
  verilogBlackBox.io.pd_ctlb_34 := io.driver_ctl.pd_ctlb.pd_ctlb_34
  verilogBlackBox.io.pd_ctlb_35 := io.driver_ctl.pd_ctlb.pd_ctlb_35
  verilogBlackBox.io.pd_ctlb_36 := io.driver_ctl.pd_ctlb.pd_ctlb_36
  verilogBlackBox.io.pd_ctlb_37 := io.driver_ctl.pd_ctlb.pd_ctlb_37
  verilogBlackBox.io.pd_ctlb_38 := io.driver_ctl.pd_ctlb.pd_ctlb_38
  verilogBlackBox.io.pd_ctlb_39 := io.driver_ctl.pd_ctlb.pd_ctlb_39
  verilogBlackBox.io.pd_ctlb_40 := io.driver_ctl.pd_ctlb.pd_ctlb_40
  verilogBlackBox.io.pd_ctlb_41 := io.driver_ctl.pd_ctlb.pd_ctlb_41
  verilogBlackBox.io.pd_ctlb_42 := io.driver_ctl.pd_ctlb.pd_ctlb_42
  verilogBlackBox.io.pd_ctlb_43 := io.driver_ctl.pd_ctlb.pd_ctlb_43
  verilogBlackBox.io.pd_ctlb_44 := io.driver_ctl.pd_ctlb.pd_ctlb_44
  verilogBlackBox.io.pd_ctlb_45 := io.driver_ctl.pd_ctlb.pd_ctlb_45
  verilogBlackBox.io.pd_ctlb_46 := io.driver_ctl.pd_ctlb.pd_ctlb_46
  verilogBlackBox.io.pd_ctlb_47 := io.driver_ctl.pd_ctlb.pd_ctlb_47
  verilogBlackBox.io.driver_en := io.driver_ctl.en
  verilogBlackBox.io.driver_en_b := io.driver_ctl.en_b
  io.clocking_ctl.VCM := verilogBlackBox.io.VCM
  io.clocking_ctl.in_buf := verilogBlackBox.io.in_buf
  io.clocking_ctl.inbm := verilogBlackBox.io.inbm
  io.clocking_ctl.inbp := verilogBlackBox.io.inbp
  io.clocking_ctl.injmb := verilogBlackBox.io.injmb
  io.clocking_ctl.injpb := verilogBlackBox.io.injpb
  io.clocking_ctl.mid := verilogBlackBox.io.mid
  io.clocking_ctl.mixer_out := verilogBlackBox.io.mixer_out
  io.clocking_ctl.mixer_outb := verilogBlackBox.io.mixer_outb
  verilogBlackBox.io.band_ctrl := "b01".U(2.W)
  verilogBlackBox.io.band_ctrlb := "b10".U(2.W)
  verilogBlackBox.io.band_sel := io.clocking_ctl.misc.band_sel
  verilogBlackBox.io.band_selb := io.clocking_ctl.misc.band_selb
  verilogBlackBox.io.mix_en := 0.U(16.W)
  verilogBlackBox.io.mix_enb := ~0.U(16.W)
  verilogBlackBox.io.mux_en := io.clocking_ctl.misc.mux_en
  verilogBlackBox.io.mux_enb := io.clocking_ctl.misc.mux_enb
  verilogBlackBox.io.ph_sel := io.clocking_ctl.misc.ph_sel
  verilogBlackBox.io.ph_selb := io.clocking_ctl.misc.ph_selb
  verilogBlackBox.io.en := io.clocking_ctl.en
  verilogBlackBox.io.enb := io.clocking_ctl.enb

  // val ctr = withClockAndReset(io.injp.asClock, !io.resetb) { RegInit(0.U((log2Ceil(Phy.SerdesRatio) - 1).W)) }
  // ctr := ctr + 1.U

  // val divClock = withClockAndReset(io.injp.asClock, !io.resetb) { RegInit(false.B) }
  // when (ctr === 0.U) {
  //   divClock := !divClock
  // }

  // val shiftReg = withClockAndReset(io.injp.asClock, !io.resetb) { RegInit(0.U(Phy.SerdesRatio.W)) }
  // shiftReg := shiftReg >> 1.U
  // when (ctr === 0.U && !divClock) {
  //   shiftReg := io.din.asTypeOf(shiftReg)
  // }

  // io.divclk := divClock.asClock
  // io.dout := shiftReg(0)

  // io.driver_ctl <> 0.U.asTypeOf(io.driver_ctl)
  // io.clocking_ctl <> 0.U.asTypeOf(io.clocking_ctl)
}

class VerilogTxLaneIO extends Bundle {
  val injp = Input(Bool())
  val injm = Input(Bool())
  val in = Input(Bool())
  val din_0 = Input(Bool())
  val din_1 = Input(Bool())
  val din_2 = Input(Bool())
  val din_3 = Input(Bool())
  val din_4 = Input(Bool())
  val din_5 = Input(Bool())
  val din_6 = Input(Bool())
  val din_7 = Input(Bool())
  val din_8 = Input(Bool())
  val din_9 = Input(Bool())
  val din_10 = Input(Bool())
  val din_11 = Input(Bool())
  val din_12 = Input(Bool())
  val din_13 = Input(Bool())
  val din_14 = Input(Bool())
  val din_15 = Input(Bool())
  val dout = Output(Bool())
  val divclk = Output(Clock())
  val resetb = Input(Bool())
  val pu_ctl_0 = Input(Bool())
  val pu_ctl_1 = Input(Bool())
  val pu_ctl_2 = Input(Bool())
  val pu_ctl_3 = Input(Bool())
  val pu_ctl_4 = Input(Bool())
  val pu_ctl_5 = Input(Bool())
  val pu_ctl_6 = Input(Bool())
  val pu_ctl_7 = Input(Bool())
  val pu_ctl_8 = Input(Bool())
  val pu_ctl_9 = Input(Bool())
  val pu_ctl_10 = Input(Bool())
  val pu_ctl_11 = Input(Bool())
  val pu_ctl_12 = Input(Bool())
  val pu_ctl_13 = Input(Bool())
  val pu_ctl_14 = Input(Bool())
  val pu_ctl_15 = Input(Bool())
  val pu_ctl_16 = Input(Bool())
  val pu_ctl_17 = Input(Bool())
  val pu_ctl_18 = Input(Bool())
  val pu_ctl_19 = Input(Bool())
  val pu_ctl_20 = Input(Bool())
  val pu_ctl_21 = Input(Bool())
  val pu_ctl_22 = Input(Bool())
  val pu_ctl_23 = Input(Bool())
  val pu_ctl_24 = Input(Bool())
  val pu_ctl_25 = Input(Bool())
  val pu_ctl_26 = Input(Bool())
  val pu_ctl_27 = Input(Bool())
  val pu_ctl_28 = Input(Bool())
  val pu_ctl_29 = Input(Bool())
  val pu_ctl_30 = Input(Bool())
  val pu_ctl_31 = Input(Bool())
  val pu_ctl_32 = Input(Bool())
  val pu_ctl_33 = Input(Bool())
  val pu_ctl_34 = Input(Bool())
  val pu_ctl_35 = Input(Bool())
  val pu_ctl_36 = Input(Bool())
  val pu_ctl_37 = Input(Bool())
  val pu_ctl_38 = Input(Bool())
  val pu_ctl_39 = Input(Bool())
  val pu_ctl_40 = Input(Bool())
  val pu_ctl_41 = Input(Bool())
  val pu_ctl_42 = Input(Bool())
  val pu_ctl_43 = Input(Bool())
  val pu_ctl_44 = Input(Bool())
  val pu_ctl_45 = Input(Bool())
  val pu_ctl_46 = Input(Bool())
  val pu_ctl_47 = Input(Bool())
  val pd_ctlb_0 = Input(Bool())
  val pd_ctlb_1 = Input(Bool())
  val pd_ctlb_2 = Input(Bool())
  val pd_ctlb_3 = Input(Bool())
  val pd_ctlb_4 = Input(Bool())
  val pd_ctlb_5 = Input(Bool())
  val pd_ctlb_6 = Input(Bool())
  val pd_ctlb_7 = Input(Bool())
  val pd_ctlb_8 = Input(Bool())
  val pd_ctlb_9 = Input(Bool())
  val pd_ctlb_10 = Input(Bool())
  val pd_ctlb_11 = Input(Bool())
  val pd_ctlb_12 = Input(Bool())
  val pd_ctlb_13 = Input(Bool())
  val pd_ctlb_14 = Input(Bool())
  val pd_ctlb_15 = Input(Bool())
  val pd_ctlb_16 = Input(Bool())
  val pd_ctlb_17 = Input(Bool())
  val pd_ctlb_18 = Input(Bool())
  val pd_ctlb_19 = Input(Bool())
  val pd_ctlb_20 = Input(Bool())
  val pd_ctlb_21 = Input(Bool())
  val pd_ctlb_22 = Input(Bool())
  val pd_ctlb_23 = Input(Bool())
  val pd_ctlb_24 = Input(Bool())
  val pd_ctlb_25 = Input(Bool())
  val pd_ctlb_26 = Input(Bool())
  val pd_ctlb_27 = Input(Bool())
  val pd_ctlb_28 = Input(Bool())
  val pd_ctlb_29 = Input(Bool())
  val pd_ctlb_30 = Input(Bool())
  val pd_ctlb_31 = Input(Bool())
  val pd_ctlb_32 = Input(Bool())
  val pd_ctlb_33 = Input(Bool())
  val pd_ctlb_34 = Input(Bool())
  val pd_ctlb_35 = Input(Bool())
  val pd_ctlb_36 = Input(Bool())
  val pd_ctlb_37 = Input(Bool())
  val pd_ctlb_38 = Input(Bool())
  val pd_ctlb_39 = Input(Bool())
  val pd_ctlb_40 = Input(Bool())
  val pd_ctlb_41 = Input(Bool())
  val pd_ctlb_42 = Input(Bool())
  val pd_ctlb_43 = Input(Bool())
  val pd_ctlb_44 = Input(Bool())
  val pd_ctlb_45 = Input(Bool())
  val pd_ctlb_46 = Input(Bool())
  val pd_ctlb_47 = Input(Bool())
  val driver_en = Input(Bool()) 
  val driver_en_b = Input(Bool()) 
  val VCM = Output(Bool())
  val in_buf = Output(Bits(8.W))
  val inbm = Output(Bool())
  val inbp = Output(Bool())
  val injmb = Output(Bool())
  val injpb = Output(Bool())
  val mid = Output(Bits(8.W))
  val mixer_out = Output(Bool())
  val mixer_outb = Output(Bool())
  val band_ctrl = Input(Bits(2.W))
  val band_ctrlb = Input(Bits(2.W))
  val band_sel = Input(Bits(2.W))
  val band_selb = Input(Bits(2.W))
  val mix_en = Input(Bits(16.W))
  val mix_enb = Input(Bits(16.W))
  val mux_en = Input(Bits(8.W))
  val mux_enb = Input(Bits(8.W))
  val ph_sel = Input(Bits(2.W))
  val ph_selb = Input(Bits(2.W))
  val en = Input(Bits(64.W))
  val enb = Input(Bits(64.W))
}

class VerilogTxLane extends BlackBox {
  val io = IO(new VerilogTxLaneIO)

  override val desiredName = "TX_data_lane"
}

class TxClkIO extends Bundle {
  val injp = Input(Bool())
  val injm = Input(Bool())
  val in = Input(Bool())
  val txckp = Output(Bool())
  val txckn = Output(Bool())
  val driver_ctl = Vec(2, new DriverControlIO)
  val VCM = Output(Bool())
  val inbm = Output(Bool())
  val inbp = Output(Bool())
  val injmb = Output(Bool())
  val injpb = Output(Bool())
  val mid = Output(Bits(8.W))
  val en = Input(Bits(64.W))
  val enb = Input(Bits(64.W))
}

class TxClk extends RawModule {
  val io = IO(new TxClkIO)

  val verilogBlackBox = Module(new VerilogTxClk)
  verilogBlackBox.io.injp := io.injp
  verilogBlackBox.io.injm := io.injm
  verilogBlackBox.io.in := io.in
  io.txckp := verilogBlackBox.io.txckp
  io.txckn := verilogBlackBox.io.txckn
  verilogBlackBox.io.driver0_pu_ctl_0  := io.driver_ctl(0).pu_ctl.pu_ctl_0
  verilogBlackBox.io.driver0_pu_ctl_1  := io.driver_ctl(0).pu_ctl.pu_ctl_1
  verilogBlackBox.io.driver0_pu_ctl_2  := io.driver_ctl(0).pu_ctl.pu_ctl_2
  verilogBlackBox.io.driver0_pu_ctl_3  := io.driver_ctl(0).pu_ctl.pu_ctl_3
  verilogBlackBox.io.driver0_pu_ctl_4  := io.driver_ctl(0).pu_ctl.pu_ctl_4
  verilogBlackBox.io.driver0_pu_ctl_5  := io.driver_ctl(0).pu_ctl.pu_ctl_5
  verilogBlackBox.io.driver0_pu_ctl_6  := io.driver_ctl(0).pu_ctl.pu_ctl_6
  verilogBlackBox.io.driver0_pu_ctl_7  := io.driver_ctl(0).pu_ctl.pu_ctl_7
  verilogBlackBox.io.driver0_pu_ctl_8  := io.driver_ctl(0).pu_ctl.pu_ctl_8
  verilogBlackBox.io.driver0_pu_ctl_9  := io.driver_ctl(0).pu_ctl.pu_ctl_9
  verilogBlackBox.io.driver0_pu_ctl_10 := io.driver_ctl(0).pu_ctl.pu_ctl_10
  verilogBlackBox.io.driver0_pu_ctl_11 := io.driver_ctl(0).pu_ctl.pu_ctl_11
  verilogBlackBox.io.driver0_pu_ctl_12 := io.driver_ctl(0).pu_ctl.pu_ctl_12
  verilogBlackBox.io.driver0_pu_ctl_13 := io.driver_ctl(0).pu_ctl.pu_ctl_13
  verilogBlackBox.io.driver0_pu_ctl_14 := io.driver_ctl(0).pu_ctl.pu_ctl_14
  verilogBlackBox.io.driver0_pu_ctl_15 := io.driver_ctl(0).pu_ctl.pu_ctl_15
  verilogBlackBox.io.driver0_pu_ctl_16 := io.driver_ctl(0).pu_ctl.pu_ctl_16
  verilogBlackBox.io.driver0_pu_ctl_17 := io.driver_ctl(0).pu_ctl.pu_ctl_17
  verilogBlackBox.io.driver0_pu_ctl_18 := io.driver_ctl(0).pu_ctl.pu_ctl_18
  verilogBlackBox.io.driver0_pu_ctl_19 := io.driver_ctl(0).pu_ctl.pu_ctl_19
  verilogBlackBox.io.driver0_pu_ctl_20 := io.driver_ctl(0).pu_ctl.pu_ctl_20
  verilogBlackBox.io.driver0_pu_ctl_21 := io.driver_ctl(0).pu_ctl.pu_ctl_21
  verilogBlackBox.io.driver0_pu_ctl_22 := io.driver_ctl(0).pu_ctl.pu_ctl_22
  verilogBlackBox.io.driver0_pu_ctl_23 := io.driver_ctl(0).pu_ctl.pu_ctl_23
  verilogBlackBox.io.driver0_pu_ctl_24 := io.driver_ctl(0).pu_ctl.pu_ctl_24
  verilogBlackBox.io.driver0_pu_ctl_25 := io.driver_ctl(0).pu_ctl.pu_ctl_25
  verilogBlackBox.io.driver0_pu_ctl_26 := io.driver_ctl(0).pu_ctl.pu_ctl_26
  verilogBlackBox.io.driver0_pu_ctl_27 := io.driver_ctl(0).pu_ctl.pu_ctl_27
  verilogBlackBox.io.driver0_pu_ctl_28 := io.driver_ctl(0).pu_ctl.pu_ctl_28
  verilogBlackBox.io.driver0_pu_ctl_29 := io.driver_ctl(0).pu_ctl.pu_ctl_29
  verilogBlackBox.io.driver0_pu_ctl_30 := io.driver_ctl(0).pu_ctl.pu_ctl_30
  verilogBlackBox.io.driver0_pu_ctl_31 := io.driver_ctl(0).pu_ctl.pu_ctl_31
  verilogBlackBox.io.driver0_pu_ctl_32 := io.driver_ctl(0).pu_ctl.pu_ctl_32
  verilogBlackBox.io.driver0_pu_ctl_33 := io.driver_ctl(0).pu_ctl.pu_ctl_33
  verilogBlackBox.io.driver0_pu_ctl_34 := io.driver_ctl(0).pu_ctl.pu_ctl_34
  verilogBlackBox.io.driver0_pu_ctl_35 := io.driver_ctl(0).pu_ctl.pu_ctl_35
  verilogBlackBox.io.driver0_pu_ctl_36 := io.driver_ctl(0).pu_ctl.pu_ctl_36
  verilogBlackBox.io.driver0_pu_ctl_37 := io.driver_ctl(0).pu_ctl.pu_ctl_37
  verilogBlackBox.io.driver0_pu_ctl_38 := io.driver_ctl(0).pu_ctl.pu_ctl_38
  verilogBlackBox.io.driver0_pu_ctl_39 := io.driver_ctl(0).pu_ctl.pu_ctl_39
  verilogBlackBox.io.driver0_pu_ctl_40 := io.driver_ctl(0).pu_ctl.pu_ctl_40
  verilogBlackBox.io.driver0_pu_ctl_41 := io.driver_ctl(0).pu_ctl.pu_ctl_41
  verilogBlackBox.io.driver0_pu_ctl_42 := io.driver_ctl(0).pu_ctl.pu_ctl_42
  verilogBlackBox.io.driver0_pu_ctl_43 := io.driver_ctl(0).pu_ctl.pu_ctl_43
  verilogBlackBox.io.driver0_pu_ctl_44 := io.driver_ctl(0).pu_ctl.pu_ctl_44
  verilogBlackBox.io.driver0_pu_ctl_45 := io.driver_ctl(0).pu_ctl.pu_ctl_45
  verilogBlackBox.io.driver0_pu_ctl_46 := io.driver_ctl(0).pu_ctl.pu_ctl_46
  verilogBlackBox.io.driver0_pu_ctl_47 := io.driver_ctl(0).pu_ctl.pu_ctl_47
  verilogBlackBox.io.driver0_pd_ctlb_0  := io.driver_ctl(0).pd_ctlb.pd_ctlb_0
  verilogBlackBox.io.driver0_pd_ctlb_1  := io.driver_ctl(0).pd_ctlb.pd_ctlb_1
  verilogBlackBox.io.driver0_pd_ctlb_2  := io.driver_ctl(0).pd_ctlb.pd_ctlb_2
  verilogBlackBox.io.driver0_pd_ctlb_3  := io.driver_ctl(0).pd_ctlb.pd_ctlb_3
  verilogBlackBox.io.driver0_pd_ctlb_4  := io.driver_ctl(0).pd_ctlb.pd_ctlb_4
  verilogBlackBox.io.driver0_pd_ctlb_5  := io.driver_ctl(0).pd_ctlb.pd_ctlb_5
  verilogBlackBox.io.driver0_pd_ctlb_6  := io.driver_ctl(0).pd_ctlb.pd_ctlb_6
  verilogBlackBox.io.driver0_pd_ctlb_7  := io.driver_ctl(0).pd_ctlb.pd_ctlb_7
  verilogBlackBox.io.driver0_pd_ctlb_8  := io.driver_ctl(0).pd_ctlb.pd_ctlb_8
  verilogBlackBox.io.driver0_pd_ctlb_9  := io.driver_ctl(0).pd_ctlb.pd_ctlb_9
  verilogBlackBox.io.driver0_pd_ctlb_10 := io.driver_ctl(0).pd_ctlb.pd_ctlb_10
  verilogBlackBox.io.driver0_pd_ctlb_11 := io.driver_ctl(0).pd_ctlb.pd_ctlb_11
  verilogBlackBox.io.driver0_pd_ctlb_12 := io.driver_ctl(0).pd_ctlb.pd_ctlb_12
  verilogBlackBox.io.driver0_pd_ctlb_13 := io.driver_ctl(0).pd_ctlb.pd_ctlb_13
  verilogBlackBox.io.driver0_pd_ctlb_14 := io.driver_ctl(0).pd_ctlb.pd_ctlb_14
  verilogBlackBox.io.driver0_pd_ctlb_15 := io.driver_ctl(0).pd_ctlb.pd_ctlb_15
  verilogBlackBox.io.driver0_pd_ctlb_16 := io.driver_ctl(0).pd_ctlb.pd_ctlb_16
  verilogBlackBox.io.driver0_pd_ctlb_17 := io.driver_ctl(0).pd_ctlb.pd_ctlb_17
  verilogBlackBox.io.driver0_pd_ctlb_18 := io.driver_ctl(0).pd_ctlb.pd_ctlb_18
  verilogBlackBox.io.driver0_pd_ctlb_19 := io.driver_ctl(0).pd_ctlb.pd_ctlb_19
  verilogBlackBox.io.driver0_pd_ctlb_20 := io.driver_ctl(0).pd_ctlb.pd_ctlb_20
  verilogBlackBox.io.driver0_pd_ctlb_21 := io.driver_ctl(0).pd_ctlb.pd_ctlb_21
  verilogBlackBox.io.driver0_pd_ctlb_22 := io.driver_ctl(0).pd_ctlb.pd_ctlb_22
  verilogBlackBox.io.driver0_pd_ctlb_23 := io.driver_ctl(0).pd_ctlb.pd_ctlb_23
  verilogBlackBox.io.driver0_pd_ctlb_24 := io.driver_ctl(0).pd_ctlb.pd_ctlb_24
  verilogBlackBox.io.driver0_pd_ctlb_25 := io.driver_ctl(0).pd_ctlb.pd_ctlb_25
  verilogBlackBox.io.driver0_pd_ctlb_26 := io.driver_ctl(0).pd_ctlb.pd_ctlb_26
  verilogBlackBox.io.driver0_pd_ctlb_27 := io.driver_ctl(0).pd_ctlb.pd_ctlb_27
  verilogBlackBox.io.driver0_pd_ctlb_28 := io.driver_ctl(0).pd_ctlb.pd_ctlb_28
  verilogBlackBox.io.driver0_pd_ctlb_29 := io.driver_ctl(0).pd_ctlb.pd_ctlb_29
  verilogBlackBox.io.driver0_pd_ctlb_30 := io.driver_ctl(0).pd_ctlb.pd_ctlb_30
  verilogBlackBox.io.driver0_pd_ctlb_31 := io.driver_ctl(0).pd_ctlb.pd_ctlb_31
  verilogBlackBox.io.driver0_pd_ctlb_32 := io.driver_ctl(0).pd_ctlb.pd_ctlb_32
  verilogBlackBox.io.driver0_pd_ctlb_33 := io.driver_ctl(0).pd_ctlb.pd_ctlb_33
  verilogBlackBox.io.driver0_pd_ctlb_34 := io.driver_ctl(0).pd_ctlb.pd_ctlb_34
  verilogBlackBox.io.driver0_pd_ctlb_35 := io.driver_ctl(0).pd_ctlb.pd_ctlb_35
  verilogBlackBox.io.driver0_pd_ctlb_36 := io.driver_ctl(0).pd_ctlb.pd_ctlb_36
  verilogBlackBox.io.driver0_pd_ctlb_37 := io.driver_ctl(0).pd_ctlb.pd_ctlb_37
  verilogBlackBox.io.driver0_pd_ctlb_38 := io.driver_ctl(0).pd_ctlb.pd_ctlb_38
  verilogBlackBox.io.driver0_pd_ctlb_39 := io.driver_ctl(0).pd_ctlb.pd_ctlb_39
  verilogBlackBox.io.driver0_pd_ctlb_40 := io.driver_ctl(0).pd_ctlb.pd_ctlb_40
  verilogBlackBox.io.driver0_pd_ctlb_41 := io.driver_ctl(0).pd_ctlb.pd_ctlb_41
  verilogBlackBox.io.driver0_pd_ctlb_42 := io.driver_ctl(0).pd_ctlb.pd_ctlb_42
  verilogBlackBox.io.driver0_pd_ctlb_43 := io.driver_ctl(0).pd_ctlb.pd_ctlb_43
  verilogBlackBox.io.driver0_pd_ctlb_44 := io.driver_ctl(0).pd_ctlb.pd_ctlb_44
  verilogBlackBox.io.driver0_pd_ctlb_45 := io.driver_ctl(0).pd_ctlb.pd_ctlb_45
  verilogBlackBox.io.driver0_pd_ctlb_46 := io.driver_ctl(0).pd_ctlb.pd_ctlb_46
  verilogBlackBox.io.driver0_pd_ctlb_47 := io.driver_ctl(0).pd_ctlb.pd_ctlb_47
  verilogBlackBox.io.driver0_en := io.driver_ctl(0).en
  verilogBlackBox.io.driver0_en_b := io.driver_ctl(0).en_b
  verilogBlackBox.io.driver1_pu_ctl_0  := io.driver_ctl(1).pu_ctl.pu_ctl_0
  verilogBlackBox.io.driver1_pu_ctl_1  := io.driver_ctl(1).pu_ctl.pu_ctl_1
  verilogBlackBox.io.driver1_pu_ctl_2  := io.driver_ctl(1).pu_ctl.pu_ctl_2
  verilogBlackBox.io.driver1_pu_ctl_3  := io.driver_ctl(1).pu_ctl.pu_ctl_3
  verilogBlackBox.io.driver1_pu_ctl_4  := io.driver_ctl(1).pu_ctl.pu_ctl_4
  verilogBlackBox.io.driver1_pu_ctl_5  := io.driver_ctl(1).pu_ctl.pu_ctl_5
  verilogBlackBox.io.driver1_pu_ctl_6  := io.driver_ctl(1).pu_ctl.pu_ctl_6
  verilogBlackBox.io.driver1_pu_ctl_7  := io.driver_ctl(1).pu_ctl.pu_ctl_7
  verilogBlackBox.io.driver1_pu_ctl_8  := io.driver_ctl(1).pu_ctl.pu_ctl_8
  verilogBlackBox.io.driver1_pu_ctl_9  := io.driver_ctl(1).pu_ctl.pu_ctl_9
  verilogBlackBox.io.driver1_pu_ctl_10 := io.driver_ctl(1).pu_ctl.pu_ctl_10
  verilogBlackBox.io.driver1_pu_ctl_11 := io.driver_ctl(1).pu_ctl.pu_ctl_11
  verilogBlackBox.io.driver1_pu_ctl_12 := io.driver_ctl(1).pu_ctl.pu_ctl_12
  verilogBlackBox.io.driver1_pu_ctl_13 := io.driver_ctl(1).pu_ctl.pu_ctl_13
  verilogBlackBox.io.driver1_pu_ctl_14 := io.driver_ctl(1).pu_ctl.pu_ctl_14
  verilogBlackBox.io.driver1_pu_ctl_15 := io.driver_ctl(1).pu_ctl.pu_ctl_15
  verilogBlackBox.io.driver1_pu_ctl_16 := io.driver_ctl(1).pu_ctl.pu_ctl_16
  verilogBlackBox.io.driver1_pu_ctl_17 := io.driver_ctl(1).pu_ctl.pu_ctl_17
  verilogBlackBox.io.driver1_pu_ctl_18 := io.driver_ctl(1).pu_ctl.pu_ctl_18
  verilogBlackBox.io.driver1_pu_ctl_19 := io.driver_ctl(1).pu_ctl.pu_ctl_19
  verilogBlackBox.io.driver1_pu_ctl_20 := io.driver_ctl(1).pu_ctl.pu_ctl_20
  verilogBlackBox.io.driver1_pu_ctl_21 := io.driver_ctl(1).pu_ctl.pu_ctl_21
  verilogBlackBox.io.driver1_pu_ctl_22 := io.driver_ctl(1).pu_ctl.pu_ctl_22
  verilogBlackBox.io.driver1_pu_ctl_23 := io.driver_ctl(1).pu_ctl.pu_ctl_23
  verilogBlackBox.io.driver1_pu_ctl_24 := io.driver_ctl(1).pu_ctl.pu_ctl_24
  verilogBlackBox.io.driver1_pu_ctl_25 := io.driver_ctl(1).pu_ctl.pu_ctl_25
  verilogBlackBox.io.driver1_pu_ctl_26 := io.driver_ctl(1).pu_ctl.pu_ctl_26
  verilogBlackBox.io.driver1_pu_ctl_27 := io.driver_ctl(1).pu_ctl.pu_ctl_27
  verilogBlackBox.io.driver1_pu_ctl_28 := io.driver_ctl(1).pu_ctl.pu_ctl_28
  verilogBlackBox.io.driver1_pu_ctl_29 := io.driver_ctl(1).pu_ctl.pu_ctl_29
  verilogBlackBox.io.driver1_pu_ctl_30 := io.driver_ctl(1).pu_ctl.pu_ctl_30
  verilogBlackBox.io.driver1_pu_ctl_31 := io.driver_ctl(1).pu_ctl.pu_ctl_31
  verilogBlackBox.io.driver1_pu_ctl_32 := io.driver_ctl(1).pu_ctl.pu_ctl_32
  verilogBlackBox.io.driver1_pu_ctl_33 := io.driver_ctl(1).pu_ctl.pu_ctl_33
  verilogBlackBox.io.driver1_pu_ctl_34 := io.driver_ctl(1).pu_ctl.pu_ctl_34
  verilogBlackBox.io.driver1_pu_ctl_35 := io.driver_ctl(1).pu_ctl.pu_ctl_35
  verilogBlackBox.io.driver1_pu_ctl_36 := io.driver_ctl(1).pu_ctl.pu_ctl_36
  verilogBlackBox.io.driver1_pu_ctl_37 := io.driver_ctl(1).pu_ctl.pu_ctl_37
  verilogBlackBox.io.driver1_pu_ctl_38 := io.driver_ctl(1).pu_ctl.pu_ctl_38
  verilogBlackBox.io.driver1_pu_ctl_39 := io.driver_ctl(1).pu_ctl.pu_ctl_39
  verilogBlackBox.io.driver1_pu_ctl_40 := io.driver_ctl(1).pu_ctl.pu_ctl_40
  verilogBlackBox.io.driver1_pu_ctl_41 := io.driver_ctl(1).pu_ctl.pu_ctl_41
  verilogBlackBox.io.driver1_pu_ctl_42 := io.driver_ctl(1).pu_ctl.pu_ctl_42
  verilogBlackBox.io.driver1_pu_ctl_43 := io.driver_ctl(1).pu_ctl.pu_ctl_43
  verilogBlackBox.io.driver1_pu_ctl_44 := io.driver_ctl(1).pu_ctl.pu_ctl_44
  verilogBlackBox.io.driver1_pu_ctl_45 := io.driver_ctl(1).pu_ctl.pu_ctl_45
  verilogBlackBox.io.driver1_pu_ctl_46 := io.driver_ctl(1).pu_ctl.pu_ctl_46
  verilogBlackBox.io.driver1_pu_ctl_47 := io.driver_ctl(1).pu_ctl.pu_ctl_47
  verilogBlackBox.io.driver1_pd_ctlb_0  := io.driver_ctl(1).pd_ctlb.pd_ctlb_0
  verilogBlackBox.io.driver1_pd_ctlb_1  := io.driver_ctl(1).pd_ctlb.pd_ctlb_1
  verilogBlackBox.io.driver1_pd_ctlb_2  := io.driver_ctl(1).pd_ctlb.pd_ctlb_2
  verilogBlackBox.io.driver1_pd_ctlb_3  := io.driver_ctl(1).pd_ctlb.pd_ctlb_3
  verilogBlackBox.io.driver1_pd_ctlb_4  := io.driver_ctl(1).pd_ctlb.pd_ctlb_4
  verilogBlackBox.io.driver1_pd_ctlb_5  := io.driver_ctl(1).pd_ctlb.pd_ctlb_5
  verilogBlackBox.io.driver1_pd_ctlb_6  := io.driver_ctl(1).pd_ctlb.pd_ctlb_6
  verilogBlackBox.io.driver1_pd_ctlb_7  := io.driver_ctl(1).pd_ctlb.pd_ctlb_7
  verilogBlackBox.io.driver1_pd_ctlb_8  := io.driver_ctl(1).pd_ctlb.pd_ctlb_8
  verilogBlackBox.io.driver1_pd_ctlb_9  := io.driver_ctl(1).pd_ctlb.pd_ctlb_9
  verilogBlackBox.io.driver1_pd_ctlb_10 := io.driver_ctl(1).pd_ctlb.pd_ctlb_10
  verilogBlackBox.io.driver1_pd_ctlb_11 := io.driver_ctl(1).pd_ctlb.pd_ctlb_11
  verilogBlackBox.io.driver1_pd_ctlb_12 := io.driver_ctl(1).pd_ctlb.pd_ctlb_12
  verilogBlackBox.io.driver1_pd_ctlb_13 := io.driver_ctl(1).pd_ctlb.pd_ctlb_13
  verilogBlackBox.io.driver1_pd_ctlb_14 := io.driver_ctl(1).pd_ctlb.pd_ctlb_14
  verilogBlackBox.io.driver1_pd_ctlb_15 := io.driver_ctl(1).pd_ctlb.pd_ctlb_15
  verilogBlackBox.io.driver1_pd_ctlb_16 := io.driver_ctl(1).pd_ctlb.pd_ctlb_16
  verilogBlackBox.io.driver1_pd_ctlb_17 := io.driver_ctl(1).pd_ctlb.pd_ctlb_17
  verilogBlackBox.io.driver1_pd_ctlb_18 := io.driver_ctl(1).pd_ctlb.pd_ctlb_18
  verilogBlackBox.io.driver1_pd_ctlb_19 := io.driver_ctl(1).pd_ctlb.pd_ctlb_19
  verilogBlackBox.io.driver1_pd_ctlb_20 := io.driver_ctl(1).pd_ctlb.pd_ctlb_20
  verilogBlackBox.io.driver1_pd_ctlb_21 := io.driver_ctl(1).pd_ctlb.pd_ctlb_21
  verilogBlackBox.io.driver1_pd_ctlb_22 := io.driver_ctl(1).pd_ctlb.pd_ctlb_22
  verilogBlackBox.io.driver1_pd_ctlb_23 := io.driver_ctl(1).pd_ctlb.pd_ctlb_23
  verilogBlackBox.io.driver1_pd_ctlb_24 := io.driver_ctl(1).pd_ctlb.pd_ctlb_24
  verilogBlackBox.io.driver1_pd_ctlb_25 := io.driver_ctl(1).pd_ctlb.pd_ctlb_25
  verilogBlackBox.io.driver1_pd_ctlb_26 := io.driver_ctl(1).pd_ctlb.pd_ctlb_26
  verilogBlackBox.io.driver1_pd_ctlb_27 := io.driver_ctl(1).pd_ctlb.pd_ctlb_27
  verilogBlackBox.io.driver1_pd_ctlb_28 := io.driver_ctl(1).pd_ctlb.pd_ctlb_28
  verilogBlackBox.io.driver1_pd_ctlb_29 := io.driver_ctl(1).pd_ctlb.pd_ctlb_29
  verilogBlackBox.io.driver1_pd_ctlb_30 := io.driver_ctl(1).pd_ctlb.pd_ctlb_30
  verilogBlackBox.io.driver1_pd_ctlb_31 := io.driver_ctl(1).pd_ctlb.pd_ctlb_31
  verilogBlackBox.io.driver1_pd_ctlb_32 := io.driver_ctl(1).pd_ctlb.pd_ctlb_32
  verilogBlackBox.io.driver1_pd_ctlb_33 := io.driver_ctl(1).pd_ctlb.pd_ctlb_33
  verilogBlackBox.io.driver1_pd_ctlb_34 := io.driver_ctl(1).pd_ctlb.pd_ctlb_34
  verilogBlackBox.io.driver1_pd_ctlb_35 := io.driver_ctl(1).pd_ctlb.pd_ctlb_35
  verilogBlackBox.io.driver1_pd_ctlb_36 := io.driver_ctl(1).pd_ctlb.pd_ctlb_36
  verilogBlackBox.io.driver1_pd_ctlb_37 := io.driver_ctl(1).pd_ctlb.pd_ctlb_37
  verilogBlackBox.io.driver1_pd_ctlb_38 := io.driver_ctl(1).pd_ctlb.pd_ctlb_38
  verilogBlackBox.io.driver1_pd_ctlb_39 := io.driver_ctl(1).pd_ctlb.pd_ctlb_39
  verilogBlackBox.io.driver1_pd_ctlb_40 := io.driver_ctl(1).pd_ctlb.pd_ctlb_40
  verilogBlackBox.io.driver1_pd_ctlb_41 := io.driver_ctl(1).pd_ctlb.pd_ctlb_41
  verilogBlackBox.io.driver1_pd_ctlb_42 := io.driver_ctl(1).pd_ctlb.pd_ctlb_42
  verilogBlackBox.io.driver1_pd_ctlb_43 := io.driver_ctl(1).pd_ctlb.pd_ctlb_43
  verilogBlackBox.io.driver1_pd_ctlb_44 := io.driver_ctl(1).pd_ctlb.pd_ctlb_44
  verilogBlackBox.io.driver1_pd_ctlb_45 := io.driver_ctl(1).pd_ctlb.pd_ctlb_45
  verilogBlackBox.io.driver1_pd_ctlb_46 := io.driver_ctl(1).pd_ctlb.pd_ctlb_46
  verilogBlackBox.io.driver1_pd_ctlb_47 := io.driver_ctl(1).pd_ctlb.pd_ctlb_47
  verilogBlackBox.io.driver1_en := io.driver_ctl(1).en
  verilogBlackBox.io.driver1_en_b := io.driver_ctl(1).en_b
  io.VCM := verilogBlackBox.io.VCM
  io.inbm := verilogBlackBox.io.inbm
  io.inbp := verilogBlackBox.io.inbp
  io.injmb := verilogBlackBox.io.injmb
  io.injpb := verilogBlackBox.io.injpb
  io.mid := verilogBlackBox.io.mid
  verilogBlackBox.io.en := io.en
  verilogBlackBox.io.enb := io.enb

  // io.txckp := io.injp
  // io.txckn := io.injm
  // 
  // io.driver0 <> 0.U.asTypeOf(io.driver0)
  // io.driver1 <> 0.U.asTypeOf(io.driver1)
  // io.driver0_en := true.B
  // io.driver1_en := true.B
  // io.driver0_en_b := false.B
  // io.driver1_en_b := false.B
}

class VerilogTxClkIO extends Bundle {
  val injp = Input(Bool())
  val injm = Input(Bool())
  val in = Input(Bool())
  val txckp = Output(Bool())
  val txckn = Output(Bool())
  val driver0_pu_ctl_0 = Input(Bool())
  val driver0_pu_ctl_1 = Input(Bool())
  val driver0_pu_ctl_2 = Input(Bool())
  val driver0_pu_ctl_3 = Input(Bool())
  val driver0_pu_ctl_4 = Input(Bool())
  val driver0_pu_ctl_5 = Input(Bool())
  val driver0_pu_ctl_6 = Input(Bool())
  val driver0_pu_ctl_7 = Input(Bool())
  val driver0_pu_ctl_8 = Input(Bool())
  val driver0_pu_ctl_9 = Input(Bool())
  val driver0_pu_ctl_10 = Input(Bool())
  val driver0_pu_ctl_11 = Input(Bool())
  val driver0_pu_ctl_12 = Input(Bool())
  val driver0_pu_ctl_13 = Input(Bool())
  val driver0_pu_ctl_14 = Input(Bool())
  val driver0_pu_ctl_15 = Input(Bool())
  val driver0_pu_ctl_16 = Input(Bool())
  val driver0_pu_ctl_17 = Input(Bool())
  val driver0_pu_ctl_18 = Input(Bool())
  val driver0_pu_ctl_19 = Input(Bool())
  val driver0_pu_ctl_20 = Input(Bool())
  val driver0_pu_ctl_21 = Input(Bool())
  val driver0_pu_ctl_22 = Input(Bool())
  val driver0_pu_ctl_23 = Input(Bool())
  val driver0_pu_ctl_24 = Input(Bool())
  val driver0_pu_ctl_25 = Input(Bool())
  val driver0_pu_ctl_26 = Input(Bool())
  val driver0_pu_ctl_27 = Input(Bool())
  val driver0_pu_ctl_28 = Input(Bool())
  val driver0_pu_ctl_29 = Input(Bool())
  val driver0_pu_ctl_30 = Input(Bool())
  val driver0_pu_ctl_31 = Input(Bool())
  val driver0_pu_ctl_32 = Input(Bool())
  val driver0_pu_ctl_33 = Input(Bool())
  val driver0_pu_ctl_34 = Input(Bool())
  val driver0_pu_ctl_35 = Input(Bool())
  val driver0_pu_ctl_36 = Input(Bool())
  val driver0_pu_ctl_37 = Input(Bool())
  val driver0_pu_ctl_38 = Input(Bool())
  val driver0_pu_ctl_39 = Input(Bool())
  val driver0_pu_ctl_40 = Input(Bool())
  val driver0_pu_ctl_41 = Input(Bool())
  val driver0_pu_ctl_42 = Input(Bool())
  val driver0_pu_ctl_43 = Input(Bool())
  val driver0_pu_ctl_44 = Input(Bool())
  val driver0_pu_ctl_45 = Input(Bool())
  val driver0_pu_ctl_46 = Input(Bool())
  val driver0_pu_ctl_47 = Input(Bool())
  val driver0_pd_ctlb_0 = Input(Bool())
  val driver0_pd_ctlb_1 = Input(Bool())
  val driver0_pd_ctlb_2 = Input(Bool())
  val driver0_pd_ctlb_3 = Input(Bool())
  val driver0_pd_ctlb_4 = Input(Bool())
  val driver0_pd_ctlb_5 = Input(Bool())
  val driver0_pd_ctlb_6 = Input(Bool())
  val driver0_pd_ctlb_7 = Input(Bool())
  val driver0_pd_ctlb_8 = Input(Bool())
  val driver0_pd_ctlb_9 = Input(Bool())
  val driver0_pd_ctlb_10 = Input(Bool())
  val driver0_pd_ctlb_11 = Input(Bool())
  val driver0_pd_ctlb_12 = Input(Bool())
  val driver0_pd_ctlb_13 = Input(Bool())
  val driver0_pd_ctlb_14 = Input(Bool())
  val driver0_pd_ctlb_15 = Input(Bool())
  val driver0_pd_ctlb_16 = Input(Bool())
  val driver0_pd_ctlb_17 = Input(Bool())
  val driver0_pd_ctlb_18 = Input(Bool())
  val driver0_pd_ctlb_19 = Input(Bool())
  val driver0_pd_ctlb_20 = Input(Bool())
  val driver0_pd_ctlb_21 = Input(Bool())
  val driver0_pd_ctlb_22 = Input(Bool())
  val driver0_pd_ctlb_23 = Input(Bool())
  val driver0_pd_ctlb_24 = Input(Bool())
  val driver0_pd_ctlb_25 = Input(Bool())
  val driver0_pd_ctlb_26 = Input(Bool())
  val driver0_pd_ctlb_27 = Input(Bool())
  val driver0_pd_ctlb_28 = Input(Bool())
  val driver0_pd_ctlb_29 = Input(Bool())
  val driver0_pd_ctlb_30 = Input(Bool())
  val driver0_pd_ctlb_31 = Input(Bool())
  val driver0_pd_ctlb_32 = Input(Bool())
  val driver0_pd_ctlb_33 = Input(Bool())
  val driver0_pd_ctlb_34 = Input(Bool())
  val driver0_pd_ctlb_35 = Input(Bool())
  val driver0_pd_ctlb_36 = Input(Bool())
  val driver0_pd_ctlb_37 = Input(Bool())
  val driver0_pd_ctlb_38 = Input(Bool())
  val driver0_pd_ctlb_39 = Input(Bool())
  val driver0_pd_ctlb_40 = Input(Bool())
  val driver0_pd_ctlb_41 = Input(Bool())
  val driver0_pd_ctlb_42 = Input(Bool())
  val driver0_pd_ctlb_43 = Input(Bool())
  val driver0_pd_ctlb_44 = Input(Bool())
  val driver0_pd_ctlb_45 = Input(Bool())
  val driver0_pd_ctlb_46 = Input(Bool())
  val driver0_pd_ctlb_47 = Input(Bool())
  val driver0_en = Input(Bool()) 
  val driver0_en_b = Input(Bool()) 
  val driver1_pu_ctl_0 = Input(Bool())
  val driver1_pu_ctl_1 = Input(Bool())
  val driver1_pu_ctl_2 = Input(Bool())
  val driver1_pu_ctl_3 = Input(Bool())
  val driver1_pu_ctl_4 = Input(Bool())
  val driver1_pu_ctl_5 = Input(Bool())
  val driver1_pu_ctl_6 = Input(Bool())
  val driver1_pu_ctl_7 = Input(Bool())
  val driver1_pu_ctl_8 = Input(Bool())
  val driver1_pu_ctl_9 = Input(Bool())
  val driver1_pu_ctl_10 = Input(Bool())
  val driver1_pu_ctl_11 = Input(Bool())
  val driver1_pu_ctl_12 = Input(Bool())
  val driver1_pu_ctl_13 = Input(Bool())
  val driver1_pu_ctl_14 = Input(Bool())
  val driver1_pu_ctl_15 = Input(Bool())
  val driver1_pu_ctl_16 = Input(Bool())
  val driver1_pu_ctl_17 = Input(Bool())
  val driver1_pu_ctl_18 = Input(Bool())
  val driver1_pu_ctl_19 = Input(Bool())
  val driver1_pu_ctl_20 = Input(Bool())
  val driver1_pu_ctl_21 = Input(Bool())
  val driver1_pu_ctl_22 = Input(Bool())
  val driver1_pu_ctl_23 = Input(Bool())
  val driver1_pu_ctl_24 = Input(Bool())
  val driver1_pu_ctl_25 = Input(Bool())
  val driver1_pu_ctl_26 = Input(Bool())
  val driver1_pu_ctl_27 = Input(Bool())
  val driver1_pu_ctl_28 = Input(Bool())
  val driver1_pu_ctl_29 = Input(Bool())
  val driver1_pu_ctl_30 = Input(Bool())
  val driver1_pu_ctl_31 = Input(Bool())
  val driver1_pu_ctl_32 = Input(Bool())
  val driver1_pu_ctl_33 = Input(Bool())
  val driver1_pu_ctl_34 = Input(Bool())
  val driver1_pu_ctl_35 = Input(Bool())
  val driver1_pu_ctl_36 = Input(Bool())
  val driver1_pu_ctl_37 = Input(Bool())
  val driver1_pu_ctl_38 = Input(Bool())
  val driver1_pu_ctl_39 = Input(Bool())
  val driver1_pu_ctl_40 = Input(Bool())
  val driver1_pu_ctl_41 = Input(Bool())
  val driver1_pu_ctl_42 = Input(Bool())
  val driver1_pu_ctl_43 = Input(Bool())
  val driver1_pu_ctl_44 = Input(Bool())
  val driver1_pu_ctl_45 = Input(Bool())
  val driver1_pu_ctl_46 = Input(Bool())
  val driver1_pu_ctl_47 = Input(Bool())
  val driver1_pd_ctlb_0 = Input(Bool())
  val driver1_pd_ctlb_1 = Input(Bool())
  val driver1_pd_ctlb_2 = Input(Bool())
  val driver1_pd_ctlb_3 = Input(Bool())
  val driver1_pd_ctlb_4 = Input(Bool())
  val driver1_pd_ctlb_5 = Input(Bool())
  val driver1_pd_ctlb_6 = Input(Bool())
  val driver1_pd_ctlb_7 = Input(Bool())
  val driver1_pd_ctlb_8 = Input(Bool())
  val driver1_pd_ctlb_9 = Input(Bool())
  val driver1_pd_ctlb_10 = Input(Bool())
  val driver1_pd_ctlb_11 = Input(Bool())
  val driver1_pd_ctlb_12 = Input(Bool())
  val driver1_pd_ctlb_13 = Input(Bool())
  val driver1_pd_ctlb_14 = Input(Bool())
  val driver1_pd_ctlb_15 = Input(Bool())
  val driver1_pd_ctlb_16 = Input(Bool())
  val driver1_pd_ctlb_17 = Input(Bool())
  val driver1_pd_ctlb_18 = Input(Bool())
  val driver1_pd_ctlb_19 = Input(Bool())
  val driver1_pd_ctlb_20 = Input(Bool())
  val driver1_pd_ctlb_21 = Input(Bool())
  val driver1_pd_ctlb_22 = Input(Bool())
  val driver1_pd_ctlb_23 = Input(Bool())
  val driver1_pd_ctlb_24 = Input(Bool())
  val driver1_pd_ctlb_25 = Input(Bool())
  val driver1_pd_ctlb_26 = Input(Bool())
  val driver1_pd_ctlb_27 = Input(Bool())
  val driver1_pd_ctlb_28 = Input(Bool())
  val driver1_pd_ctlb_29 = Input(Bool())
  val driver1_pd_ctlb_30 = Input(Bool())
  val driver1_pd_ctlb_31 = Input(Bool())
  val driver1_pd_ctlb_32 = Input(Bool())
  val driver1_pd_ctlb_33 = Input(Bool())
  val driver1_pd_ctlb_34 = Input(Bool())
  val driver1_pd_ctlb_35 = Input(Bool())
  val driver1_pd_ctlb_36 = Input(Bool())
  val driver1_pd_ctlb_37 = Input(Bool())
  val driver1_pd_ctlb_38 = Input(Bool())
  val driver1_pd_ctlb_39 = Input(Bool())
  val driver1_pd_ctlb_40 = Input(Bool())
  val driver1_pd_ctlb_41 = Input(Bool())
  val driver1_pd_ctlb_42 = Input(Bool())
  val driver1_pd_ctlb_43 = Input(Bool())
  val driver1_pd_ctlb_44 = Input(Bool())
  val driver1_pd_ctlb_45 = Input(Bool())
  val driver1_pd_ctlb_46 = Input(Bool())
  val driver1_pd_ctlb_47 = Input(Bool())
  val driver1_en = Input(Bool()) 
  val driver1_en_b = Input(Bool()) 
  val VCM = Output(Bool())
  val inbm = Output(Bool())
  val inbp = Output(Bool())
  val injmb = Output(Bool())
  val injpb = Output(Bool())
  val mid = Output(Bits(8.W))
  val en = Input(Bits(64.W))
  val enb = Input(Bits(64.W))
}

class VerilogTxClk extends BlackBox {
  val io = IO(new VerilogTxClkIO)

  override val desiredName = "TX_clk_tile"
}

class TxDriverIO extends Bundle {
  val din = Input(Bool())
  val dout = Output(Bool())
  val driver_ctl = new DriverControlIO
}

class TxDriver extends RawModule {
  val io = IO(new TxDriverIO)

  val verilogBlackBox = Module(new VerilogTxDriver)
  verilogBlackBox.io.clkin := io.din
  io.dout := verilogBlackBox.io.clkout
  verilogBlackBox.io.pu_ctl_0  := io.driver_ctl.pu_ctl.pu_ctl_0
  verilogBlackBox.io.pu_ctl_1  := io.driver_ctl.pu_ctl.pu_ctl_1
  verilogBlackBox.io.pu_ctl_2  := io.driver_ctl.pu_ctl.pu_ctl_2
  verilogBlackBox.io.pu_ctl_3  := io.driver_ctl.pu_ctl.pu_ctl_3
  verilogBlackBox.io.pu_ctl_4  := io.driver_ctl.pu_ctl.pu_ctl_4
  verilogBlackBox.io.pu_ctl_5  := io.driver_ctl.pu_ctl.pu_ctl_5
  verilogBlackBox.io.pu_ctl_6  := io.driver_ctl.pu_ctl.pu_ctl_6
  verilogBlackBox.io.pu_ctl_7  := io.driver_ctl.pu_ctl.pu_ctl_7
  verilogBlackBox.io.pu_ctl_8  := io.driver_ctl.pu_ctl.pu_ctl_8
  verilogBlackBox.io.pu_ctl_9  := io.driver_ctl.pu_ctl.pu_ctl_9
  verilogBlackBox.io.pu_ctl_10 := io.driver_ctl.pu_ctl.pu_ctl_10
  verilogBlackBox.io.pu_ctl_11 := io.driver_ctl.pu_ctl.pu_ctl_11
  verilogBlackBox.io.pu_ctl_12 := io.driver_ctl.pu_ctl.pu_ctl_12
  verilogBlackBox.io.pu_ctl_13 := io.driver_ctl.pu_ctl.pu_ctl_13
  verilogBlackBox.io.pu_ctl_14 := io.driver_ctl.pu_ctl.pu_ctl_14
  verilogBlackBox.io.pu_ctl_15 := io.driver_ctl.pu_ctl.pu_ctl_15
  verilogBlackBox.io.pu_ctl_16 := io.driver_ctl.pu_ctl.pu_ctl_16
  verilogBlackBox.io.pu_ctl_17 := io.driver_ctl.pu_ctl.pu_ctl_17
  verilogBlackBox.io.pu_ctl_18 := io.driver_ctl.pu_ctl.pu_ctl_18
  verilogBlackBox.io.pu_ctl_19 := io.driver_ctl.pu_ctl.pu_ctl_19
  verilogBlackBox.io.pu_ctl_20 := io.driver_ctl.pu_ctl.pu_ctl_20
  verilogBlackBox.io.pu_ctl_21 := io.driver_ctl.pu_ctl.pu_ctl_21
  verilogBlackBox.io.pu_ctl_22 := io.driver_ctl.pu_ctl.pu_ctl_22
  verilogBlackBox.io.pu_ctl_23 := io.driver_ctl.pu_ctl.pu_ctl_23
  verilogBlackBox.io.pu_ctl_24 := io.driver_ctl.pu_ctl.pu_ctl_24
  verilogBlackBox.io.pu_ctl_25 := io.driver_ctl.pu_ctl.pu_ctl_25
  verilogBlackBox.io.pu_ctl_26 := io.driver_ctl.pu_ctl.pu_ctl_26
  verilogBlackBox.io.pu_ctl_27 := io.driver_ctl.pu_ctl.pu_ctl_27
  verilogBlackBox.io.pu_ctl_28 := io.driver_ctl.pu_ctl.pu_ctl_28
  verilogBlackBox.io.pu_ctl_29 := io.driver_ctl.pu_ctl.pu_ctl_29
  verilogBlackBox.io.pu_ctl_30 := io.driver_ctl.pu_ctl.pu_ctl_30
  verilogBlackBox.io.pu_ctl_31 := io.driver_ctl.pu_ctl.pu_ctl_31
  verilogBlackBox.io.pu_ctl_32 := io.driver_ctl.pu_ctl.pu_ctl_32
  verilogBlackBox.io.pu_ctl_33 := io.driver_ctl.pu_ctl.pu_ctl_33
  verilogBlackBox.io.pu_ctl_34 := io.driver_ctl.pu_ctl.pu_ctl_34
  verilogBlackBox.io.pu_ctl_35 := io.driver_ctl.pu_ctl.pu_ctl_35
  verilogBlackBox.io.pu_ctl_36 := io.driver_ctl.pu_ctl.pu_ctl_36
  verilogBlackBox.io.pu_ctl_37 := io.driver_ctl.pu_ctl.pu_ctl_37
  verilogBlackBox.io.pu_ctl_38 := io.driver_ctl.pu_ctl.pu_ctl_38
  verilogBlackBox.io.pu_ctl_39 := io.driver_ctl.pu_ctl.pu_ctl_39
  verilogBlackBox.io.pu_ctl_40 := io.driver_ctl.pu_ctl.pu_ctl_40
  verilogBlackBox.io.pu_ctl_41 := io.driver_ctl.pu_ctl.pu_ctl_41
  verilogBlackBox.io.pu_ctl_42 := io.driver_ctl.pu_ctl.pu_ctl_42
  verilogBlackBox.io.pu_ctl_43 := io.driver_ctl.pu_ctl.pu_ctl_43
  verilogBlackBox.io.pu_ctl_44 := io.driver_ctl.pu_ctl.pu_ctl_44
  verilogBlackBox.io.pu_ctl_45 := io.driver_ctl.pu_ctl.pu_ctl_45
  verilogBlackBox.io.pu_ctl_46 := io.driver_ctl.pu_ctl.pu_ctl_46
  verilogBlackBox.io.pu_ctl_47 := io.driver_ctl.pu_ctl.pu_ctl_47
  verilogBlackBox.io.pd_ctlb_0  := io.driver_ctl.pd_ctlb.pd_ctlb_0
  verilogBlackBox.io.pd_ctlb_1  := io.driver_ctl.pd_ctlb.pd_ctlb_1
  verilogBlackBox.io.pd_ctlb_2  := io.driver_ctl.pd_ctlb.pd_ctlb_2
  verilogBlackBox.io.pd_ctlb_3  := io.driver_ctl.pd_ctlb.pd_ctlb_3
  verilogBlackBox.io.pd_ctlb_4  := io.driver_ctl.pd_ctlb.pd_ctlb_4
  verilogBlackBox.io.pd_ctlb_5  := io.driver_ctl.pd_ctlb.pd_ctlb_5
  verilogBlackBox.io.pd_ctlb_6  := io.driver_ctl.pd_ctlb.pd_ctlb_6
  verilogBlackBox.io.pd_ctlb_7  := io.driver_ctl.pd_ctlb.pd_ctlb_7
  verilogBlackBox.io.pd_ctlb_8  := io.driver_ctl.pd_ctlb.pd_ctlb_8
  verilogBlackBox.io.pd_ctlb_9  := io.driver_ctl.pd_ctlb.pd_ctlb_9
  verilogBlackBox.io.pd_ctlb_10 := io.driver_ctl.pd_ctlb.pd_ctlb_10
  verilogBlackBox.io.pd_ctlb_11 := io.driver_ctl.pd_ctlb.pd_ctlb_11
  verilogBlackBox.io.pd_ctlb_12 := io.driver_ctl.pd_ctlb.pd_ctlb_12
  verilogBlackBox.io.pd_ctlb_13 := io.driver_ctl.pd_ctlb.pd_ctlb_13
  verilogBlackBox.io.pd_ctlb_14 := io.driver_ctl.pd_ctlb.pd_ctlb_14
  verilogBlackBox.io.pd_ctlb_15 := io.driver_ctl.pd_ctlb.pd_ctlb_15
  verilogBlackBox.io.pd_ctlb_16 := io.driver_ctl.pd_ctlb.pd_ctlb_16
  verilogBlackBox.io.pd_ctlb_17 := io.driver_ctl.pd_ctlb.pd_ctlb_17
  verilogBlackBox.io.pd_ctlb_18 := io.driver_ctl.pd_ctlb.pd_ctlb_18
  verilogBlackBox.io.pd_ctlb_19 := io.driver_ctl.pd_ctlb.pd_ctlb_19
  verilogBlackBox.io.pd_ctlb_20 := io.driver_ctl.pd_ctlb.pd_ctlb_20
  verilogBlackBox.io.pd_ctlb_21 := io.driver_ctl.pd_ctlb.pd_ctlb_21
  verilogBlackBox.io.pd_ctlb_22 := io.driver_ctl.pd_ctlb.pd_ctlb_22
  verilogBlackBox.io.pd_ctlb_23 := io.driver_ctl.pd_ctlb.pd_ctlb_23
  verilogBlackBox.io.pd_ctlb_24 := io.driver_ctl.pd_ctlb.pd_ctlb_24
  verilogBlackBox.io.pd_ctlb_25 := io.driver_ctl.pd_ctlb.pd_ctlb_25
  verilogBlackBox.io.pd_ctlb_26 := io.driver_ctl.pd_ctlb.pd_ctlb_26
  verilogBlackBox.io.pd_ctlb_27 := io.driver_ctl.pd_ctlb.pd_ctlb_27
  verilogBlackBox.io.pd_ctlb_28 := io.driver_ctl.pd_ctlb.pd_ctlb_28
  verilogBlackBox.io.pd_ctlb_29 := io.driver_ctl.pd_ctlb.pd_ctlb_29
  verilogBlackBox.io.pd_ctlb_30 := io.driver_ctl.pd_ctlb.pd_ctlb_30
  verilogBlackBox.io.pd_ctlb_31 := io.driver_ctl.pd_ctlb.pd_ctlb_31
  verilogBlackBox.io.pd_ctlb_32 := io.driver_ctl.pd_ctlb.pd_ctlb_32
  verilogBlackBox.io.pd_ctlb_33 := io.driver_ctl.pd_ctlb.pd_ctlb_33
  verilogBlackBox.io.pd_ctlb_34 := io.driver_ctl.pd_ctlb.pd_ctlb_34
  verilogBlackBox.io.pd_ctlb_35 := io.driver_ctl.pd_ctlb.pd_ctlb_35
  verilogBlackBox.io.pd_ctlb_36 := io.driver_ctl.pd_ctlb.pd_ctlb_36
  verilogBlackBox.io.pd_ctlb_37 := io.driver_ctl.pd_ctlb.pd_ctlb_37
  verilogBlackBox.io.pd_ctlb_38 := io.driver_ctl.pd_ctlb.pd_ctlb_38
  verilogBlackBox.io.pd_ctlb_39 := io.driver_ctl.pd_ctlb.pd_ctlb_39
  verilogBlackBox.io.pd_ctlb_40 := io.driver_ctl.pd_ctlb.pd_ctlb_40
  verilogBlackBox.io.pd_ctlb_41 := io.driver_ctl.pd_ctlb.pd_ctlb_41
  verilogBlackBox.io.pd_ctlb_42 := io.driver_ctl.pd_ctlb.pd_ctlb_42
  verilogBlackBox.io.pd_ctlb_43 := io.driver_ctl.pd_ctlb.pd_ctlb_43
  verilogBlackBox.io.pd_ctlb_44 := io.driver_ctl.pd_ctlb.pd_ctlb_44
  verilogBlackBox.io.pd_ctlb_45 := io.driver_ctl.pd_ctlb.pd_ctlb_45
  verilogBlackBox.io.pd_ctlb_46 := io.driver_ctl.pd_ctlb.pd_ctlb_46
  verilogBlackBox.io.pd_ctlb_47 := io.driver_ctl.pd_ctlb.pd_ctlb_47
  verilogBlackBox.io.en := io.driver_ctl.en
  verilogBlackBox.io.en_b := io.driver_ctl.en_b

  // io.dout := io.din
}
class VerilogTxDriverIO extends Bundle {
  val clkin = Input(Bool())
  val clkout = Output(Bool())
  val pu_ctl_0 = Input(Bool())
  val pu_ctl_1 = Input(Bool())
  val pu_ctl_2 = Input(Bool())
  val pu_ctl_3 = Input(Bool())
  val pu_ctl_4 = Input(Bool())
  val pu_ctl_5 = Input(Bool())
  val pu_ctl_6 = Input(Bool())
  val pu_ctl_7 = Input(Bool())
  val pu_ctl_8 = Input(Bool())
  val pu_ctl_9 = Input(Bool())
  val pu_ctl_10 = Input(Bool())
  val pu_ctl_11 = Input(Bool())
  val pu_ctl_12 = Input(Bool())
  val pu_ctl_13 = Input(Bool())
  val pu_ctl_14 = Input(Bool())
  val pu_ctl_15 = Input(Bool())
  val pu_ctl_16 = Input(Bool())
  val pu_ctl_17 = Input(Bool())
  val pu_ctl_18 = Input(Bool())
  val pu_ctl_19 = Input(Bool())
  val pu_ctl_20 = Input(Bool())
  val pu_ctl_21 = Input(Bool())
  val pu_ctl_22 = Input(Bool())
  val pu_ctl_23 = Input(Bool())
  val pu_ctl_24 = Input(Bool())
  val pu_ctl_25 = Input(Bool())
  val pu_ctl_26 = Input(Bool())
  val pu_ctl_27 = Input(Bool())
  val pu_ctl_28 = Input(Bool())
  val pu_ctl_29 = Input(Bool())
  val pu_ctl_30 = Input(Bool())
  val pu_ctl_31 = Input(Bool())
  val pu_ctl_32 = Input(Bool())
  val pu_ctl_33 = Input(Bool())
  val pu_ctl_34 = Input(Bool())
  val pu_ctl_35 = Input(Bool())
  val pu_ctl_36 = Input(Bool())
  val pu_ctl_37 = Input(Bool())
  val pu_ctl_38 = Input(Bool())
  val pu_ctl_39 = Input(Bool())
  val pu_ctl_40 = Input(Bool())
  val pu_ctl_41 = Input(Bool())
  val pu_ctl_42 = Input(Bool())
  val pu_ctl_43 = Input(Bool())
  val pu_ctl_44 = Input(Bool())
  val pu_ctl_45 = Input(Bool())
  val pu_ctl_46 = Input(Bool())
  val pu_ctl_47 = Input(Bool())
  val pd_ctlb_0 = Input(Bool())
  val pd_ctlb_1 = Input(Bool())
  val pd_ctlb_2 = Input(Bool())
  val pd_ctlb_3 = Input(Bool())
  val pd_ctlb_4 = Input(Bool())
  val pd_ctlb_5 = Input(Bool())
  val pd_ctlb_6 = Input(Bool())
  val pd_ctlb_7 = Input(Bool())
  val pd_ctlb_8 = Input(Bool())
  val pd_ctlb_9 = Input(Bool())
  val pd_ctlb_10 = Input(Bool())
  val pd_ctlb_11 = Input(Bool())
  val pd_ctlb_12 = Input(Bool())
  val pd_ctlb_13 = Input(Bool())
  val pd_ctlb_14 = Input(Bool())
  val pd_ctlb_15 = Input(Bool())
  val pd_ctlb_16 = Input(Bool())
  val pd_ctlb_17 = Input(Bool())
  val pd_ctlb_18 = Input(Bool())
  val pd_ctlb_19 = Input(Bool())
  val pd_ctlb_20 = Input(Bool())
  val pd_ctlb_21 = Input(Bool())
  val pd_ctlb_22 = Input(Bool())
  val pd_ctlb_23 = Input(Bool())
  val pd_ctlb_24 = Input(Bool())
  val pd_ctlb_25 = Input(Bool())
  val pd_ctlb_26 = Input(Bool())
  val pd_ctlb_27 = Input(Bool())
  val pd_ctlb_28 = Input(Bool())
  val pd_ctlb_29 = Input(Bool())
  val pd_ctlb_30 = Input(Bool())
  val pd_ctlb_31 = Input(Bool())
  val pd_ctlb_32 = Input(Bool())
  val pd_ctlb_33 = Input(Bool())
  val pd_ctlb_34 = Input(Bool())
  val pd_ctlb_35 = Input(Bool())
  val pd_ctlb_36 = Input(Bool())
  val pd_ctlb_37 = Input(Bool())
  val pd_ctlb_38 = Input(Bool())
  val pd_ctlb_39 = Input(Bool())
  val pd_ctlb_40 = Input(Bool())
  val pd_ctlb_41 = Input(Bool())
  val pd_ctlb_42 = Input(Bool())
  val pd_ctlb_43 = Input(Bool())
  val pd_ctlb_44 = Input(Bool())
  val pd_ctlb_45 = Input(Bool())
  val pd_ctlb_46 = Input(Bool())
  val pd_ctlb_47 = Input(Bool())
  val en = Input(Bool()) 
  val en_b = Input(Bool()) 
}

class VerilogTxDriver extends BlackBox {
  val io = IO(new VerilogTxDriverIO)

  override val desiredName = "txclk"
}
